#!/usr/bin/env python3

#  Automatically generated by kazoo/templates/glue/language_wrappers/mini-cv-python
#  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#  This is an input file for the DMT tool "aadl2glueC". It is imported
#  at runtime and its role is to populate DMT's AST prior to executing the
#  B mapper functions.

from dmt.commonPy import aadlAST as ast

ast.g_apLevelContainers = dict()

# Interface "SHKFDIRTC"
sp = ast.ApLevelContainer("SHKFDIRTC")
ast.g_apLevelContainers["SHKFDIRTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::RawTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("packet", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RawTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("SHKFDIRTC", "packet", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("SHKFDIRTC", "packet", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Associated_Queue_Size = 1
# Taste::Communication_Layer = default
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = SHKFDIRTC
# Taste::RCMoperationKind = sporadic
# Taste::RCMperiod = 0 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["SHKFDIRTC", "Ada", "Ada", "hkfdirmng", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "trigger"
sp = ast.ApLevelContainer("trigger")
ast.g_apLevelContainers["trigger"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::Interface_Cyclic_Offset = 1000
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 16384
# Taste::InterfaceName = trigger
# Taste::RCMoperationKind = cyclic
# Taste::RCMperiod = 1000 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["trigger", "Ada", "Ada", "hkfdirmng", sp._fpgaConfigurations])
sp._language = "Ada"

# Interface "DoHousekeeping"
sp = ast.ApLevelContainer("DoHousekeeping")
ast.g_apLevelContainers["DoHousekeeping"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = DoHousekeeping
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["DoHousekeeping", "Ada", "Ada", "hkfdirmng", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "ExecHKFDIRTC"
sp = ast.ApLevelContainer("ExecHKFDIRTC")
ast.g_apLevelContainers["ExecHKFDIRTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::RawTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("packet", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RawTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("ExecHKFDIRTC", "packet", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("ExecHKFDIRTC", "packet", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = ExecHKFDIRTC
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["ExecHKFDIRTC", "Ada", "Ada", "hkfdirmng", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "SEvAction"
sp = ast.ApLevelContainer("SEvAction")
ast.g_apLevelContainers["SEvAction"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Associated_Queue_Size = 10
# Taste::Communication_Layer = default
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = SEvAction
# Taste::labelInheritance = true
# Taste::RCMoperationKind = sporadic
# Taste::RCMperiod = 0 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["SEvAction", "Ada", "Ada", "hkfdirmng", sp._fpgaConfigurations])
sp._language = "Ada"

