-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by TASTE (kazoo/templates/glue/language_wrappers/ri_adb/function.tmplt)
package body Hkfdirmng_RI is

   procedure Dohousekeeping (Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Dohousekeeping
         (Dest_PID : asn1sccPID)
         with Import,
              Convention => C,
              Link_Name  => "hkfdirmng_RI_DoHousekeeping_To_PID";
   begin
         C_Dohousekeeping (Dest_PID);
   end Dohousekeeping;
   
   
   
   procedure Exechkfdirtc
      (Packet : in out asn1SccRawtc;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Exechkfdirtc
         (Dest_PID : asn1sccPID;
          Packet : in out asn1SccRawtc)
         with Import,
              Convention => C,
              Link_Name  => "hkfdirmng_RI_ExecHKFDIRTC_To_PID";
   begin
         C_Exechkfdirtc (Dest_PID, packet);
   end Exechkfdirtc;
   
   
   
   procedure Sevaction (Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Sevaction
         (Dest_PID : asn1sccPID)
         with Import,
              Convention => C,
              Link_Name  => "hkfdirmng_RI_SEvAction_To_PID";
   begin
         C_Sevaction (Dest_PID);
   end Sevaction;

end Hkfdirmng_RI;
