/* Body file for function HKFDIRMng
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "hkfdirmng_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void hkfdirmng_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

extern void init_legacy(void);
extern unsigned legacy_initialized;
unsigned hkfdirmng_initialized = 0;
void init_hkfdirmng(void)
{
   if (0 == hkfdirmng_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused __attribute__((unused)) = getTimeInMilliseconds();
      hkfdirmng_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      extern void hkfdirmng_startup(void);
      hkfdirmng_startup();
      puts ("[TASTE] Initialization completed for function HKFDIRMng");
      hkfdirmng_initialized = 2;
   }
}
void hkfdirmng_SHKFDIRTC
      (const char *IN_packet, size_t IN_packet_len)

{
   sender_pid = hkfdirmng_shkfdirtc_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: hkfdirmng,shkfdirtc,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void hkfdirmng_PI_SHKFDIRTC
      (const asn1SccRawTC *);





   // Call user code
   hkfdirmng_PI_SHKFDIRTC ((asn1SccRawTC *)IN_packet);

   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *hkfdirmng_state(void);
      printf ("INNER_SDL_STATE: hkfdirmng,%s\n", hkfdirmng_state());
      fflush(stdout);
   }
}




void hkfdirmng_trigger(void)
{
   sender_pid = hkfdirmng_trigger_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: hkfdirmng,trigger,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void hkfdirmng_PI_trigger(void);
   hkfdirmng_PI_trigger();
   // puts ("hkfdirmng_trigger called");
   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *hkfdirmng_state(void);
      printf ("INNER_SDL_STATE: hkfdirmng,%s\n", hkfdirmng_state());
      fflush(stdout);
   }
}

