#ifndef GENERATED_ASN1SCC_dataview_uniq_H
#define GENERATED_ASN1SCC_dataview_uniq_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef struct {
    int nCount;
    byte arr[256];
} RawTC;


flag RawTC_Equal(const RawTC* pVal1, const RawTC* pVal2);

#define ERR_RAWTC		1  /*(SIZE (0..256))*/
flag RawTC_IsConstraintValid(const RawTC* pVal, int* pErrCode);

void RawTC_Initialize(RawTC* pVal);

#define ERR_UPER_ENCODE_RAWTC		2  /**/
#define RawTC_REQUIRED_BYTES_FOR_ENCODING       258
#define RawTC_REQUIRED_BITS_FOR_ENCODING        2057

flag RawTC_Encode(const RawTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_RAWTC		3  /**/
flag RawTC_Decode(RawTC* pVal, BitStream* pBitStrm, int* pErrCode);

#define RawTC_REQUIRED_BYTES_FOR_ACN_ENCODING       258
#define RawTC_REQUIRED_BITS_FOR_ACN_ENCODING        2057

#define ERR_ACN_ENCODE_RAWTC		4  /**/

flag RawTC_ACN_Encode(const RawTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_RAWTC		5  /**/
flag RawTC_ACN_Decode(RawTC* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    RxTC_not_accepted = 0,
    RxTC_accepted = 1
} RxTC;

// please use the following macros to avoid breaking code.
#define RxTC_not_accepted RxTC_not_accepted
#define RxTC_accepted RxTC_accepted

flag RxTC_Equal(const RxTC* pVal1, const RxTC* pVal2);

#define ERR_RXTC		6  /*not-accepted | accepted*/
flag RxTC_IsConstraintValid(const RxTC* pVal, int* pErrCode);

void RxTC_Initialize(RxTC* pVal);

#define ERR_UPER_ENCODE_RXTC		7  /**/
#define RxTC_REQUIRED_BYTES_FOR_ENCODING       1
#define RxTC_REQUIRED_BITS_FOR_ENCODING        1

flag RxTC_Encode(const RxTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_RXTC		8  /**/
flag RxTC_Decode(RxTC* pVal, BitStream* pBitStrm, int* pErrCode);

#define RxTC_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define RxTC_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_RXTC		9  /**/

flag RxTC_ACN_Encode(const RxTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_RXTC		10  /**/
flag RxTC_ACN_Decode(RxTC* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    FwdCommand_to_reboot = 0,
    FwdCommand_exec_prio_tc = 1,
    FwdCommand_fwdhk_fdir_tc = 2,
    FwdCommand_fwdbkgtc = 3
} FwdCommand;

// please use the following macros to avoid breaking code.
#define FwdCommand_to_reboot FwdCommand_to_reboot
#define FwdCommand_exec_prio_tc FwdCommand_exec_prio_tc
#define FwdCommand_fwdhk_fdir_tc FwdCommand_fwdhk_fdir_tc
#define FwdCommand_fwdbkgtc FwdCommand_fwdbkgtc

flag FwdCommand_Equal(const FwdCommand* pVal1, const FwdCommand* pVal2);

#define ERR_FWDCOMMAND		11  /*to-reboot | exec-prio-tc | fwdhk-fdir-tc | fwdbkgtc*/
flag FwdCommand_IsConstraintValid(const FwdCommand* pVal, int* pErrCode);

void FwdCommand_Initialize(FwdCommand* pVal);

#define ERR_UPER_ENCODE_FWDCOMMAND		12  /**/
#define FwdCommand_REQUIRED_BYTES_FOR_ENCODING       1
#define FwdCommand_REQUIRED_BITS_FOR_ENCODING        2

flag FwdCommand_Encode(const FwdCommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_FWDCOMMAND		13  /**/
flag FwdCommand_Decode(FwdCommand* pVal, BitStream* pBitStrm, int* pErrCode);

#define FwdCommand_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define FwdCommand_REQUIRED_BITS_FOR_ACN_ENCODING        2

#define ERR_ACN_ENCODE_FWDCOMMAND		14  /**/

flag FwdCommand_ACN_Encode(const FwdCommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_FWDCOMMAND		15  /**/
flag FwdCommand_ACN_Decode(FwdCommand* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag GPendingEvAction;


flag GPendingEvAction_Equal(const GPendingEvAction* pVal1, const GPendingEvAction* pVal2);

#define ERR_GPENDINGEVACTION		16  /**/
flag GPendingEvAction_IsConstraintValid(const GPendingEvAction* pVal, int* pErrCode);

void GPendingEvAction_Initialize(GPendingEvAction* pVal);

#define ERR_UPER_ENCODE_GPENDINGEVACTION		17  /**/
#define GPendingEvAction_REQUIRED_BYTES_FOR_ENCODING       1
#define GPendingEvAction_REQUIRED_BITS_FOR_ENCODING        1

flag GPendingEvAction_Encode(const GPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GPENDINGEVACTION		18  /**/
flag GPendingEvAction_Decode(GPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode);

#define GPendingEvAction_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define GPendingEvAction_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_GPENDINGEVACTION		19  /**/

flag GPendingEvAction_ACN_Encode(const GPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GPENDINGEVACTION		20  /**/
flag GPendingEvAction_ACN_Decode(GPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag GToReboot;


flag GToReboot_Equal(const GToReboot* pVal1, const GToReboot* pVal2);

#define ERR_GTOREBOOT		21  /**/
flag GToReboot_IsConstraintValid(const GToReboot* pVal, int* pErrCode);

void GToReboot_Initialize(GToReboot* pVal);

#define ERR_UPER_ENCODE_GTOREBOOT		22  /**/
#define GToReboot_REQUIRED_BYTES_FOR_ENCODING       1
#define GToReboot_REQUIRED_BITS_FOR_ENCODING        1

flag GToReboot_Encode(const GToReboot* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GTOREBOOT		23  /**/
flag GToReboot_Decode(GToReboot* pVal, BitStream* pBitStrm, int* pErrCode);

#define GToReboot_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define GToReboot_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_GTOREBOOT		24  /**/

flag GToReboot_ACN_Encode(const GToReboot* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GTOREBOOT		25  /**/
flag GToReboot_ACN_Decode(GToReboot* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag GFwToHK_FDIR;


flag GFwToHK_FDIR_Equal(const GFwToHK_FDIR* pVal1, const GFwToHK_FDIR* pVal2);

#define ERR_GFWTOHK_FDIR		26  /**/
flag GFwToHK_FDIR_IsConstraintValid(const GFwToHK_FDIR* pVal, int* pErrCode);

void GFwToHK_FDIR_Initialize(GFwToHK_FDIR* pVal);

#define ERR_UPER_ENCODE_GFWTOHK_FDIR		27  /**/
#define GFwToHK_FDIR_REQUIRED_BYTES_FOR_ENCODING       1
#define GFwToHK_FDIR_REQUIRED_BITS_FOR_ENCODING        1

flag GFwToHK_FDIR_Encode(const GFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GFWTOHK_FDIR		28  /**/
flag GFwToHK_FDIR_Decode(GFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode);

#define GFwToHK_FDIR_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define GFwToHK_FDIR_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_GFWTOHK_FDIR		29  /**/

flag GFwToHK_FDIR_ACN_Encode(const GFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GFWTOHK_FDIR		30  /**/
flag GFwToHK_FDIR_ACN_Decode(GFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag GFwToBKG;


flag GFwToBKG_Equal(const GFwToBKG* pVal1, const GFwToBKG* pVal2);

#define ERR_GFWTOBKG		31  /**/
flag GFwToBKG_IsConstraintValid(const GFwToBKG* pVal, int* pErrCode);

void GFwToBKG_Initialize(GFwToBKG* pVal);

#define ERR_UPER_ENCODE_GFWTOBKG		32  /**/
#define GFwToBKG_REQUIRED_BYTES_FOR_ENCODING       1
#define GFwToBKG_REQUIRED_BITS_FOR_ENCODING        1

flag GFwToBKG_Encode(const GFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GFWTOBKG		33  /**/
flag GFwToBKG_Decode(GFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode);

#define GFwToBKG_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define GFwToBKG_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_GFWTOBKG		34  /**/

flag GFwToBKG_ACN_Encode(const GFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GFWTOBKG		35  /**/
flag GFwToBKG_ACN_Decode(GFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- Telecommand --------------------------------------------*/
typedef asn1SccUint Telecommand_service_type;

typedef asn1SccUint Telecommand_subservice_type;

typedef struct {
    byte arr[3];
} Telecommand_param;

typedef struct {
    Telecommand_service_type service_type;
    Telecommand_subservice_type subservice_type;
    Telecommand_param param;

} Telecommand;

flag Telecommand_service_type_Equal(const Telecommand_service_type* pVal1, const Telecommand_service_type* pVal2);

flag Telecommand_subservice_type_Equal(const Telecommand_subservice_type* pVal1, const Telecommand_subservice_type* pVal2);

flag Telecommand_param_Equal(const Telecommand_param* pVal1, const Telecommand_param* pVal2);

flag Telecommand_Equal(const Telecommand* pVal1, const Telecommand* pVal2);

#define ERR_TELECOMMAND_SERVICE_TYPE		36  /*(0..255)*/
flag Telecommand_service_type_IsConstraintValid(const Telecommand_service_type* pVal, int* pErrCode);

#define ERR_TELECOMMAND_SUBSERVICE_TYPE		41  /*(0..255)*/
flag Telecommand_subservice_type_IsConstraintValid(const Telecommand_subservice_type* pVal, int* pErrCode);

#define ERR_TELECOMMAND_PARAM		46  /*(SIZE (3))*/
flag Telecommand_param_IsConstraintValid(const Telecommand_param* pVal, int* pErrCode);

#define ERR_TELECOMMAND		51  /**/
flag Telecommand_IsConstraintValid(const Telecommand* pVal, int* pErrCode);

void Telecommand_service_type_Initialize(Telecommand_service_type* pVal);
void Telecommand_subservice_type_Initialize(Telecommand_subservice_type* pVal);
void Telecommand_param_Initialize(Telecommand_param* pVal);
void Telecommand_Initialize(Telecommand* pVal);

#define ERR_UPER_ENCODE_TELECOMMAND		52  /**/
#define ERR_UPER_ENCODE_TELECOMMAND_SERVICE_TYPE		37  /**/
#define ERR_UPER_ENCODE_TELECOMMAND_SUBSERVICE_TYPE		42  /**/
#define ERR_UPER_ENCODE_TELECOMMAND_PARAM		47  /**/
#define Telecommand_REQUIRED_BYTES_FOR_ENCODING       5
#define Telecommand_REQUIRED_BITS_FOR_ENCODING        40

flag Telecommand_Encode(const Telecommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_TELECOMMAND		53  /**/
#define ERR_UPER_DECODE_TELECOMMAND_SERVICE_TYPE		38  /**/
#define ERR_UPER_DECODE_TELECOMMAND_SUBSERVICE_TYPE		43  /**/
#define ERR_UPER_DECODE_TELECOMMAND_PARAM		48  /**/
flag Telecommand_Decode(Telecommand* pVal, BitStream* pBitStrm, int* pErrCode);

#define Telecommand_REQUIRED_BYTES_FOR_ACN_ENCODING       5
#define Telecommand_REQUIRED_BITS_FOR_ACN_ENCODING        40

#define ERR_ACN_ENCODE_TELECOMMAND		54  /**/
#define ERR_ACN_ENCODE_TELECOMMAND_SERVICE_TYPE		39  /**/
#define ERR_ACN_ENCODE_TELECOMMAND_SUBSERVICE_TYPE		44  /**/
#define ERR_ACN_ENCODE_TELECOMMAND_PARAM		49  /**/

flag Telecommand_ACN_Encode(const Telecommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_TELECOMMAND		55  /**/
#define ERR_ACN_DECODE_TELECOMMAND_SERVICE_TYPE		40  /**/
#define ERR_ACN_DECODE_TELECOMMAND_SUBSERVICE_TYPE		45  /**/
#define ERR_ACN_DECODE_TELECOMMAND_PARAM		50  /**/
flag Telecommand_ACN_Decode(Telecommand* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1Real Pr_time;


flag Pr_time_Equal(const Pr_time* pVal1, const Pr_time* pVal2);

#define ERR_PR_TIME		56  /*(0.0..1000000.0)*/
flag Pr_time_IsConstraintValid(const Pr_time* pVal, int* pErrCode);

void Pr_time_Initialize(Pr_time* pVal);

#define ERR_UPER_ENCODE_PR_TIME		57  /**/
#define Pr_time_REQUIRED_BYTES_FOR_ENCODING       13
#define Pr_time_REQUIRED_BITS_FOR_ENCODING        104

flag Pr_time_Encode(const Pr_time* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PR_TIME		58  /**/
flag Pr_time_Decode(Pr_time* pVal, BitStream* pBitStrm, int* pErrCode);

#define Pr_time_REQUIRED_BYTES_FOR_ACN_ENCODING       13
#define Pr_time_REQUIRED_BITS_FOR_ACN_ENCODING        104

#define ERR_ACN_ENCODE_PR_TIME		59  /**/

flag Pr_time_ACN_Encode(const Pr_time* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PR_TIME		60  /**/
flag Pr_time_ACN_Decode(Pr_time* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint T_Int32;


flag T_Int32_Equal(const T_Int32* pVal1, const T_Int32* pVal2);

#define ERR_T_INT32		61  /*(-2147483648 .. 2147483647)*/
flag T_Int32_IsConstraintValid(const T_Int32* pVal, int* pErrCode);

void T_Int32_Initialize(T_Int32* pVal);

#define ERR_UPER_ENCODE_T_INT32		62  /**/
#define T_Int32_REQUIRED_BYTES_FOR_ENCODING       4
#define T_Int32_REQUIRED_BITS_FOR_ENCODING        32

flag T_Int32_Encode(const T_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT32		63  /**/
flag T_Int32_Decode(T_Int32* pVal, BitStream* pBitStrm, int* pErrCode);

#define T_Int32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define T_Int32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_INT32		64  /**/

flag T_Int32_ACN_Encode(const T_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_INT32		65  /**/
flag T_Int32_ACN_Decode(T_Int32* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint T_UInt32;


flag T_UInt32_Equal(const T_UInt32* pVal1, const T_UInt32* pVal2);

#define ERR_T_UINT32		66  /*(0 .. 4294967295)*/
flag T_UInt32_IsConstraintValid(const T_UInt32* pVal, int* pErrCode);

void T_UInt32_Initialize(T_UInt32* pVal);

#define ERR_UPER_ENCODE_T_UINT32		67  /**/
#define T_UInt32_REQUIRED_BYTES_FOR_ENCODING       4
#define T_UInt32_REQUIRED_BITS_FOR_ENCODING        32

flag T_UInt32_Encode(const T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT32		68  /**/
flag T_UInt32_Decode(T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);

#define T_UInt32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define T_UInt32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_UINT32		69  /**/

flag T_UInt32_ACN_Encode(const T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT32		70  /**/
flag T_UInt32_ACN_Decode(T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- T_Runtime_Error --------------------------------------------*/

typedef enum {
    T_Runtime_Error_NONE,
    T_Runtime_Error_noerror_PRESENT,
    T_Runtime_Error_encodeerror_PRESENT,
    T_Runtime_Error_decodeerror_PRESENT
} T_Runtime_Error_selection;

typedef union {
    T_UInt32 noerror;
    T_Int32 encodeerror;
    T_Int32 decodeerror;
} T_Runtime_Error_unchecked_union;

typedef struct {
    T_Runtime_Error_selection kind;

    T_Runtime_Error_unchecked_union u;
} T_Runtime_Error;

flag T_Runtime_Error_Equal(const T_Runtime_Error* pVal1, const T_Runtime_Error* pVal2);

#define ERR_T_RUNTIME_ERROR		101  /**/
#define ERR_T_RUNTIME_ERROR_NOERROR_2		76  /**/
#define ERR_T_RUNTIME_ERROR_ENCODEERROR_2		86  /**/
#define ERR_T_RUNTIME_ERROR_DECODEERROR_2		96  /**/
flag T_Runtime_Error_IsConstraintValid(const T_Runtime_Error* pVal, int* pErrCode);

void T_Runtime_Error_Initialize(T_Runtime_Error* pVal);

#define ERR_UPER_ENCODE_T_RUNTIME_ERROR		102  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_NOERROR_2		77  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		87  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		97  /**/
#define T_Runtime_Error_REQUIRED_BYTES_FOR_ENCODING       5
#define T_Runtime_Error_REQUIRED_BITS_FOR_ENCODING        34

flag T_Runtime_Error_Encode(const T_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_RUNTIME_ERROR		103  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_NOERROR_2		78  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		88  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		98  /**/
flag T_Runtime_Error_Decode(T_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);

#define T_Runtime_Error_REQUIRED_BYTES_FOR_ACN_ENCODING       5
#define T_Runtime_Error_REQUIRED_BITS_FOR_ACN_ENCODING        34

#define ERR_ACN_ENCODE_T_RUNTIME_ERROR		104  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_NOERROR_2		79  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		89  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		99  /**/

flag T_Runtime_Error_ACN_Encode(const T_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_RUNTIME_ERROR		105  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_NOERROR_2		80  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		90  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		100  /**/
flag T_Runtime_Error_ACN_Decode(T_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint T_Int8;


flag T_Int8_Equal(const T_Int8* pVal1, const T_Int8* pVal2);

#define ERR_T_INT8		106  /*(-128 .. 127)*/
flag T_Int8_IsConstraintValid(const T_Int8* pVal, int* pErrCode);

void T_Int8_Initialize(T_Int8* pVal);

#define ERR_UPER_ENCODE_T_INT8		107  /**/
#define T_Int8_REQUIRED_BYTES_FOR_ENCODING       1
#define T_Int8_REQUIRED_BITS_FOR_ENCODING        8

flag T_Int8_Encode(const T_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT8		108  /**/
flag T_Int8_Decode(T_Int8* pVal, BitStream* pBitStrm, int* pErrCode);

#define T_Int8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define T_Int8_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_T_INT8		109  /**/

flag T_Int8_ACN_Encode(const T_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_INT8		110  /**/
flag T_Int8_ACN_Decode(T_Int8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint T_UInt8;


flag T_UInt8_Equal(const T_UInt8* pVal1, const T_UInt8* pVal2);

#define ERR_T_UINT8		111  /*(0 .. 255)*/
flag T_UInt8_IsConstraintValid(const T_UInt8* pVal, int* pErrCode);

void T_UInt8_Initialize(T_UInt8* pVal);

#define ERR_UPER_ENCODE_T_UINT8		112  /**/
#define T_UInt8_REQUIRED_BYTES_FOR_ENCODING       1
#define T_UInt8_REQUIRED_BITS_FOR_ENCODING        8

flag T_UInt8_Encode(const T_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT8		113  /**/
flag T_UInt8_Decode(T_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);

#define T_UInt8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define T_UInt8_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_T_UINT8		114  /**/

flag T_UInt8_ACN_Encode(const T_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT8		115  /**/
flag T_UInt8_ACN_Decode(T_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag T_Boolean;


flag T_Boolean_Equal(const T_Boolean* pVal1, const T_Boolean* pVal2);

#define ERR_T_BOOLEAN		116  /**/
flag T_Boolean_IsConstraintValid(const T_Boolean* pVal, int* pErrCode);

void T_Boolean_Initialize(T_Boolean* pVal);

#define ERR_UPER_ENCODE_T_BOOLEAN		117  /**/
#define T_Boolean_REQUIRED_BYTES_FOR_ENCODING       1
#define T_Boolean_REQUIRED_BITS_FOR_ENCODING        1

flag T_Boolean_Encode(const T_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_BOOLEAN		118  /**/
flag T_Boolean_Decode(T_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);

#define T_Boolean_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define T_Boolean_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_T_BOOLEAN		119  /**/

flag T_Boolean_ACN_Encode(const T_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_BOOLEAN		120  /**/
flag T_Boolean_ACN_Decode(T_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- T_Null_Record --------------------------------------------*/
typedef struct {

} T_Null_Record;

flag T_Null_Record_Equal(const T_Null_Record* pVal1, const T_Null_Record* pVal2);

#define ERR_T_NULL_RECORD		121  /**/
flag T_Null_Record_IsConstraintValid(const T_Null_Record* pVal, int* pErrCode);

void T_Null_Record_Initialize(T_Null_Record* pVal);

#define T_Null_Record_REQUIRED_BYTES_FOR_ENCODING       0
#define T_Null_Record_REQUIRED_BITS_FOR_ENCODING        0

flag T_Null_Record_Encode(const T_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag T_Null_Record_Decode(T_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);

#define T_Null_Record_REQUIRED_BYTES_FOR_ACN_ENCODING       0
#define T_Null_Record_REQUIRED_BITS_FOR_ACN_ENCODING        0


flag T_Null_Record_ACN_Encode(const T_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag T_Null_Record_ACN_Decode(T_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint PID_Range;


flag PID_Range_Equal(const PID_Range* pVal1, const PID_Range* pVal2);

#define ERR_PID_RANGE		126  /*(0..5)*/
flag PID_Range_IsConstraintValid(const PID_Range* pVal, int* pErrCode);

void PID_Range_Initialize(PID_Range* pVal);

#define ERR_UPER_ENCODE_PID_RANGE		127  /**/
#define PID_Range_REQUIRED_BYTES_FOR_ENCODING       1
#define PID_Range_REQUIRED_BITS_FOR_ENCODING        3

flag PID_Range_Encode(const PID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID_RANGE		128  /**/
flag PID_Range_Decode(PID_Range* pVal, BitStream* pBitStrm, int* pErrCode);

#define PID_Range_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define PID_Range_REQUIRED_BITS_FOR_ACN_ENCODING        3

#define ERR_ACN_ENCODE_PID_RANGE		129  /**/

flag PID_Range_ACN_Encode(const PID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PID_RANGE		130  /**/
flag PID_Range_ACN_Decode(PID_Range* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    PID_bkgtcexec = 0,
    PID_hkfdirmng = 1,
    PID_irq = 2,
    PID_legacy = 3,
    PID_tcmanager = 4,
    PID_env = 5
} PID;

// please use the following macros to avoid breaking code.
#define PID_bkgtcexec PID_bkgtcexec
#define PID_hkfdirmng PID_hkfdirmng
#define PID_irq PID_irq
#define PID_legacy PID_legacy
#define PID_tcmanager PID_tcmanager
#define PID_env PID_env

flag PID_Equal(const PID* pVal1, const PID* pVal2);

#define ERR_PID		131  /*bkgtcexec | hkfdirmng | irq | legacy | tcmanager | env*/
flag PID_IsConstraintValid(const PID* pVal, int* pErrCode);

void PID_Initialize(PID* pVal);

#define ERR_UPER_ENCODE_PID		132  /**/
#define PID_REQUIRED_BYTES_FOR_ENCODING       1
#define PID_REQUIRED_BITS_FOR_ENCODING        3

flag PID_Encode(const PID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID		133  /**/
flag PID_Decode(PID* pVal, BitStream* pBitStrm, int* pErrCode);

#define PID_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define PID_REQUIRED_BITS_FOR_ACN_ENCODING        3

#define ERR_ACN_ENCODE_PID		134  /**/

flag PID_ACN_Encode(const PID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PID		135  /**/
flag PID_ACN_Decode(PID* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
