/* Header file for function IRQ
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void irq_startup(void);

/* Provided interfaces */
void irq_PI_Poll( void );

/* Required interfaces */
extern void irq_RI_newTC( const asn1SccTelecommand * );


#ifdef __cplusplus
}
#endif

