/* Header file for function Legacy
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm_if-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#include "C_ASN1_Types.h"
#include <stdio.h>
extern long long getTimeInMilliseconds(void);
#ifdef __cplusplus
extern "C" {
#endif

#include "legacy.h"

// Function initialization - calls user startup code of all dependent functions
void init_legacy(void);


/* Provided interfaces */
void legacy_DoHousekeeping(void);


void legacy_ExecBKGTC
      (const char *IN_packet, size_t IN_packet_len);



void legacy_ExecHKFDIRTC
      (const char *IN_packet, size_t IN_packet_len);



void legacy_HandleTC
      (char *OUT_route, size_t *OUT_route_len,
       char *OUT_packet, size_t *OUT_packet_len);



void legacy_Init(void);


void legacy_NewEvAction
      (char *OUT_accepted, size_t *OUT_accepted_len);



void legacy_NewRxTC
      (const char *IN_tc, size_t IN_tc_len,
       char *OUT_accepted, size_t *OUT_accepted_len);



void legacy_PollTC
      (char *OUT_accepted, size_t *OUT_accepted_len);



void legacy_Reboot(void);


#ifdef __cplusplus
}
#endif

