#!/usr/bin/env python3

#  Automatically generated by kazoo/templates/glue/language_wrappers/mini-cv-python
#  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#  This is an input file for the DMT tool "aadl2glueC". It is imported
#  at runtime and its role is to populate DMT's AST prior to executing the
#  B mapper functions.

from dmt.commonPy import aadlAST as ast

ast.g_apLevelContainers = dict()

# Interface "DoHousekeeping"
sp = ast.ApLevelContainer("DoHousekeeping")
ast.g_apLevelContainers["DoHousekeeping"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = DoHousekeeping
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["DoHousekeeping", "C", "C", "legacy", sp._fpgaConfigurations])
sp._language = "C"


# Interface "ExecBKGTC"
sp = ast.ApLevelContainer("ExecBKGTC")
ast.g_apLevelContainers["ExecBKGTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::RawTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("packet", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RawTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("ExecBKGTC", "packet", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("ExecBKGTC", "packet", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = ExecBKGTC
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["ExecBKGTC", "C", "C", "legacy", sp._fpgaConfigurations])
sp._language = "C"


# Interface "ExecHKFDIRTC"
sp = ast.ApLevelContainer("ExecHKFDIRTC")
ast.g_apLevelContainers["ExecHKFDIRTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::RawTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("packet", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RawTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("ExecHKFDIRTC", "packet", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("ExecHKFDIRTC", "packet", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = ExecHKFDIRTC
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["ExecHKFDIRTC", "C", "C", "legacy", sp._fpgaConfigurations])
sp._language = "C"


# Interface "HandleTC"
sp = ast.ApLevelContainer("HandleTC")
ast.g_apLevelContainers["HandleTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::FwdCommand")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("route", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "FwdCommand"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("HandleTC", "route", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("HandleTC", "route", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::RawTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("packet", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RawTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("HandleTC", "packet", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("HandleTC", "packet", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = HandleTC
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["HandleTC", "C", "C", "legacy", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Init"
sp = ast.ApLevelContainer("Init")
ast.g_apLevelContainers["Init"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Init
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Init", "C", "C", "legacy", sp._fpgaConfigurations])
sp._language = "C"


# Interface "NewEvAction"
sp = ast.ApLevelContainer("NewEvAction")
ast.g_apLevelContainers["NewEvAction"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::RxTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("accepted", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RxTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("NewEvAction", "accepted", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("NewEvAction", "accepted", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = NewEvAction
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["NewEvAction", "C", "C", "legacy", sp._fpgaConfigurations])
sp._language = "C"


# Interface "NewRxTC"
sp = ast.ApLevelContainer("NewRxTC")
ast.g_apLevelContainers["NewRxTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::Telecommand")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("tc", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "Telecommand"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("NewRxTC", "tc", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("NewRxTC", "tc", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::RxTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("accepted", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RxTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("NewRxTC", "accepted", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("NewRxTC", "accepted", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = NewRxTC
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["NewRxTC", "C", "C", "legacy", sp._fpgaConfigurations])
sp._language = "C"


# Interface "PollTC"
sp = ast.ApLevelContainer("PollTC")
ast.g_apLevelContainers["PollTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::RxTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("accepted", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RxTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("PollTC", "accepted", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("PollTC", "accepted", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = PollTC
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["PollTC", "C", "C", "legacy", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Reboot"
sp = ast.ApLevelContainer("Reboot")
ast.g_apLevelContainers["Reboot"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Reboot
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Reboot", "C", "C", "legacy", sp._fpgaConfigurations])
sp._language = "C"



