/* ASN.1 System configuration file for function Legacy
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/system_config/function.tmplt)
 */
#define __NEED_RawTC_NATIVE


#define __NEED_RawTC_NATIVE


#define __NEED_FwdCommand_NATIVE
#define __NEED_RawTC_NATIVE




#define __NEED_RxTC_NATIVE


#define __NEED_Telecommand_NATIVE
#define __NEED_RxTC_NATIVE


#define __NEED_RxTC_NATIVE

