/* Body file for function Legacy
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "legacy_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void legacy_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned legacy_initialized = 0;
void init_legacy(void)
{
   if (0 == legacy_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused __attribute__((unused)) = getTimeInMilliseconds();
      legacy_initialized = 1;
      // Call user code startup function
      extern void legacy_startup(void);
      legacy_startup();
      puts ("[TASTE] Initialization completed for function Legacy");
      legacy_initialized = 2;
   }
}
void legacy_DoHousekeeping(void)
{
   sender_pid = legacy_dohousekeeping_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: legacy,dohousekeeping,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void legacy_PI_DoHousekeeping(void);
   legacy_PI_DoHousekeeping();
   // puts ("legacy_dohousekeeping called");
}




void legacy_ExecBKGTC
      (const char *IN_packet, size_t IN_packet_len)

{
   sender_pid = legacy_execbkgtc_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: legacy,execbkgtc,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void legacy_PI_ExecBKGTC
      (const asn1SccRawTC *);





   // Call user code
   legacy_PI_ExecBKGTC ((asn1SccRawTC *)IN_packet);

}




void legacy_ExecHKFDIRTC
      (const char *IN_packet, size_t IN_packet_len)

{
   sender_pid = legacy_exechkfdirtc_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: legacy,exechkfdirtc,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void legacy_PI_ExecHKFDIRTC
      (const asn1SccRawTC *);





   // Call user code
   legacy_PI_ExecHKFDIRTC ((asn1SccRawTC *)IN_packet);

}




void legacy_HandleTC
      (char *OUT_route, size_t *OUT_route_len,
       char *OUT_packet, size_t *OUT_packet_len)

{
   sender_pid = legacy_handletc_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: legacy,handletc,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void legacy_PI_HandleTC
      (asn1SccFwdCommand *,
       asn1SccRawTC *);





   // Call user code
   legacy_PI_HandleTC ((asn1SccFwdCommand *)OUT_route, (asn1SccRawTC *)OUT_packet);

}




void legacy_Init(void)
{
   sender_pid = legacy_init_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: legacy,init,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void legacy_PI_Init(void);
   legacy_PI_Init();
   // puts ("legacy_init called");
}




void legacy_NewEvAction
      (char *OUT_accepted, size_t *OUT_accepted_len)

{
   sender_pid = legacy_newevaction_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: legacy,newevaction,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void legacy_PI_NewEvAction
      (asn1SccRxTC *);





   // Call user code
   legacy_PI_NewEvAction ((asn1SccRxTC *)OUT_accepted);

}




void legacy_NewRxTC
      (const char *IN_tc, size_t IN_tc_len,
       char *OUT_accepted, size_t *OUT_accepted_len)

{
   sender_pid = legacy_newrxtc_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: legacy,newrxtc,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void legacy_PI_NewRxTC
      (const asn1SccTelecommand *,
       asn1SccRxTC *);





   // Call user code
   legacy_PI_NewRxTC ((asn1SccTelecommand *)IN_tc, (asn1SccRxTC *)OUT_accepted);

}




void legacy_PollTC
      (char *OUT_accepted, size_t *OUT_accepted_len)

{
   sender_pid = legacy_polltc_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: legacy,polltc,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void legacy_PI_PollTC
      (asn1SccRxTC *);





   // Call user code
   legacy_PI_PollTC ((asn1SccRxTC *)OUT_accepted);

}




void legacy_Reboot(void)
{
   sender_pid = legacy_reboot_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: legacy,reboot,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void legacy_PI_Reboot(void);
   legacy_PI_Reboot();
   // puts ("legacy_reboot called");
}

