/* Body file for function BKGTCExec
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "bkgtcexec_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void bkgtcexec_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned bkgtcexec_initialized = 0;
void init_bkgtcexec(void)
{
   if (0 == bkgtcexec_initialized) {
      bkgtcexec_initialized = 1;
      // Call user code startup function
      extern void bkgtcexec_startup(void);
      bkgtcexec_startup();
      puts ("[TASTE] Initialization completed for function BKGTCExec");
      bkgtcexec_initialized = 2;
   }
}
void bkgtcexec_SBKGTC(void)
{
   sender_pid = bkgtcexec_sbkgtc_get_sender();

   //  Directly call user code, no parameters to pass
   extern void bkgtcexec_PI_SBKGTC(void);
   bkgtcexec_PI_SBKGTC();
   // puts ("bkgtcexec_sbkgtc called");
}

