// C++ body file for function Legacy
// Generated by TASTE (kazoo/templates/skeletons/cpp-body/function.tmplt)
// You can edit this file, it will not be overwritten

#include "legacy.h"
#include "legacy_state.h"

#include "../../../../../asw_pus_rtems_5_0_leon3/asw/components/cctcmanager/include/public/cctcmanager_iface_v1.h"

#include <iostream>

// Define and use function state inside this context structure
// avoid defining global/static variable elsewhere
legacy_state ctxt_legacy;


void legacy_startup(void)
{
   // Write your initialisation code
   // You may call sporadic interfaces and start timers
   // std::cout << "[Legacy] Startup" << std::endl;
}

void legacy_PI_HandleTC(void)
{
   // Write your code here
}

extern "C" void FInit(void){
    std::cout << "[Legacy] Dentro de la funcion FInit" << std::endl;
    CCTCManager::RxTC.MaskIRQ();
    CCTCManager::RxTC.InstallHandler();
    pus_services_startup(&CCTCManager::RxTC);
    CCTCManager::RxTC.UnMaskIRQ();
    std::cout << "[Legacy CPP] Saliendo de la funcion FInit" << std::endl;
}

void legacy_PI_Init(void)
{
    FInit();
}


void legacy_PI_NewEvAction(void)
{
   // Write your code here
}


void legacy_PI_Reboot(void)
{
   // Write your code here
}


