-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- (Generated by TASTE/Kazoo - $TOOL_SRC/kazoo/templates/glue/language_wrappers/simu_pi_adb/function.tmplt)
package body Tcmanager_PI is

   procedure Update_States_For_Synchronous_Calls (Global_State : asn1SccSystem_State) is
   begin
      --  No synchronous RIs are connected to this function
      null;
   end Update_States_For_Synchronous_Calls;

   procedure Update_Global_State_After_Synchronous_Calls (Global_State : in out asn1SccSystem_State)  is
   begin
      --  No synchronous RIs are connected to this function
      null;
   end Update_Global_State_After_Synchronous_Calls;

   procedure Startup (Global_State : in out asn1SccSystem_State) is
   begin
      --  Initialize the global state after startup function has run
      Tcmanager.Startup;
      Global_State.Tcmanager := Tcmanager.Ctxt;
   end Startup;

   procedure Continuous_Signals (Global_State : in out asn1SccSystem_State) is
   begin
      Tcmanager.Ctxt := Global_State.Tcmanager;
      Tcmanager.Execute_Transition (Tcmanager.CS_Only);
      Global_State.Tcmanager := Tcmanager.Ctxt;
   end Continuous_Signals;

   --  Provided interfaces
   procedure Trigger (Global_State : in out asn1SccSystem_State;
                                  Sender_PID   : asn1SccPID := asn1SccEnv) is
   begin
      -- Set the current context (provided by the simulation API)
      Tcmanager.Ctxt := Global_State.Tcmanager;
      Tcmanager.Ctxt.Sender := Sender_PID;
      --  If user code calls synchronous RIs, set their state too
      Update_States_For_Synchronous_Calls (Global_State);
      Tcmanager.Trigger;
      -- Update the global state
      Global_State.Tcmanager := Tcmanager.Ctxt;
      --  If user code called synchronous RIs, populate their state
      Update_Global_State_After_Synchronous_Calls (Global_State);
   end Trigger;

end Tcmanager_PI;
