#!/usr/bin/env python3

#  Automatically generated by kazoo/templates/glue/language_wrappers/mini-cv-python
#  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#  This is an input file for the DMT tool "aadl2glueC". It is imported
#  at runtime and its role is to populate DMT's AST prior to executing the
#  B mapper functions.

from dmt.commonPy import aadlAST as ast

ast.g_apLevelContainers = dict()

# Interface "SBKGTC"
sp = ast.ApLevelContainer("SBKGTC")
ast.g_apLevelContainers["SBKGTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::RawTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("packet", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RawTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("SBKGTC", "packet", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("SBKGTC", "packet", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Associated_Queue_Size = 1
# Taste::Communication_Layer = default
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = SBKGTC
# Taste::RCMoperationKind = sporadic
# Taste::RCMperiod = 0 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["SBKGTC", "Ada", "Ada", "bkgtcexec", sp._fpgaConfigurations])
sp._language = "Ada"

# Interface "ExecBKGTC"
sp = ast.ApLevelContainer("ExecBKGTC")
ast.g_apLevelContainers["ExecBKGTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::RawTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("packet", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RawTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("ExecBKGTC", "packet", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("ExecBKGTC", "packet", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = ExecBKGTC
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["ExecBKGTC", "Ada", "Ada", "bkgtcexec", sp._fpgaConfigurations])
sp._language = "Ada"

