/* Body file for function BKGTCExec
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "bkgtcexec_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void bkgtcexec_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

extern void init_legacy(void);
extern unsigned legacy_initialized;
unsigned bkgtcexec_initialized = 0;
void init_bkgtcexec(void)
{
   if (0 == bkgtcexec_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused __attribute__((unused)) = getTimeInMilliseconds();
      bkgtcexec_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      extern void bkgtcexec_startup(void);
      bkgtcexec_startup();
      puts ("[TASTE] Initialization completed for function BKGTCExec");
      bkgtcexec_initialized = 2;
   }
}
void bkgtcexec_SBKGTC
      (const char *IN_packet, size_t IN_packet_len)

{
   sender_pid = bkgtcexec_sbkgtc_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: bkgtcexec,sbkgtc,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void bkgtcexec_PI_SBKGTC
      (const asn1SccRawTC *);





   // Call user code
   bkgtcexec_PI_SBKGTC ((asn1SccRawTC *)IN_packet);

   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *bkgtcexec_state(void);
      printf ("INNER_SDL_STATE: bkgtcexec,%s\n", bkgtcexec_state());
      fflush(stdout);
   }
}

