-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by TASTE (kazoo/templates/glue/language_wrappers/ri_adb/function.tmplt)
package body Bkgtcexec_RI is

   procedure Execbkgtc
      (Packet : in out asn1SccRawtc;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Execbkgtc
         (Dest_PID : asn1sccPID;
          Packet : in out asn1SccRawtc)
         with Import,
              Convention => C,
              Link_Name  => "bkgtcexec_RI_ExecBKGTC_To_PID";
   begin
         C_Execbkgtc (Dest_PID, packet);
   end Execbkgtc;

end Bkgtcexec_RI;
