/* ASN.1 System configuration file for function BKGTCExec
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/system_config/function.tmplt)
 */
#define __NEED_RawTC_NATIVE
#define __NEED_RawTC_NATIVE
