-- DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
-- Generated by TASTE (kazoo/templates/glue/language_wrappers/ri_adb/function.tmplt)
package body Tcmanager_RI is

   procedure Handletc
      (Route  : out asn1SccFwdcommand;
       Packet : out asn1SccRawtc;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Handletc
         (Dest_PID : asn1sccPID;
          Route  : out asn1SccFwdcommand;
          Packet : out asn1SccRawtc)
         with Import,
              Convention => C,
              Link_Name  => "tcmanager_RI_HandleTC_To_PID";
   begin
         C_Handletc (Dest_PID, route, packet);
   end Handletc;
   
   
   
   procedure Init (Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Init
         (Dest_PID : asn1sccPID)
         with Import,
              Convention => C,
              Link_Name  => "tcmanager_RI_Init_To_PID";
   begin
         C_Init (Dest_PID);
   end Init;
   
   
   
   procedure Newevaction
      (Accepted : out asn1SccRxtc;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Newevaction
         (Dest_PID : asn1sccPID;
          Accepted : out asn1SccRxtc)
         with Import,
              Convention => C,
              Link_Name  => "tcmanager_RI_NewEvAction_To_PID";
   begin
         C_Newevaction (Dest_PID, accepted);
   end Newevaction;
   
   
   
   procedure Newrxtc
      (Tc       : in out asn1SccTelecommand;
       Accepted :    out asn1SccRxtc;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Newrxtc
         (Dest_PID : asn1sccPID;
          Tc       : in out asn1SccTelecommand;
          Accepted :    out asn1SccRxtc)
         with Import,
              Convention => C,
              Link_Name  => "tcmanager_RI_NewRxTC_To_PID";
   begin
         C_Newrxtc (Dest_PID, tc, accepted);
   end Newrxtc;
   
   
   
   procedure Polltc
      (Accepted : out asn1SccRxtc;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Polltc
         (Dest_PID : asn1sccPID;
          Accepted : out asn1SccRxtc)
         with Import,
              Convention => C,
              Link_Name  => "tcmanager_RI_PollTC_To_PID";
   begin
         C_Polltc (Dest_PID, accepted);
   end Polltc;
   
   
   
   procedure Reboot (Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Reboot
         (Dest_PID : asn1sccPID)
         with Import,
              Convention => C,
              Link_Name  => "tcmanager_RI_Reboot_To_PID";
   begin
         C_Reboot (Dest_PID);
   end Reboot;
   
   
   
   procedure Sbkgtc
      (Packet : in out asn1SccRawtc;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Sbkgtc
         (Dest_PID : asn1sccPID;
          Packet : in out asn1SccRawtc)
         with Import,
              Convention => C,
              Link_Name  => "tcmanager_RI_SBKGTC_To_PID";
   begin
         C_Sbkgtc (Dest_PID, packet);
   end Sbkgtc;
   
   
   
   procedure Shkfdirtc
      (Packet : in out asn1SccRawtc;
       Dest_PID : asn1sccPID := asn1sccEnv) is
      procedure C_Shkfdirtc
         (Dest_PID : asn1sccPID;
          Packet : in out asn1SccRawtc)
         with Import,
              Convention => C,
              Link_Name  => "tcmanager_RI_SHKFDIRTC_To_PID";
   begin
         C_Shkfdirtc (Dest_PID, packet);
   end Shkfdirtc;

end Tcmanager_RI;
