#!/usr/bin/env python3

#  Automatically generated by kazoo/templates/glue/language_wrappers/mini-cv-python
#  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#  This is an input file for the DMT tool "aadl2glueC". It is imported
#  at runtime and its role is to populate DMT's AST prior to executing the
#  B mapper functions.

from dmt.commonPy import aadlAST as ast

ast.g_apLevelContainers = dict()

# Interface "SEvAction"
sp = ast.ApLevelContainer("SEvAction")
ast.g_apLevelContainers["SEvAction"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Associated_Queue_Size = 10
# Taste::Communication_Layer = default
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = SEvAction
# Taste::RCMoperationKind = sporadic
# Taste::RCMperiod = 0 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["SEvAction", "Ada", "Ada", "tcmanager", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "poll"
sp = ast.ApLevelContainer("poll")
ast.g_apLevelContainers["poll"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::Interface_Cyclic_Offset = 1000
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 16384
# Taste::InterfaceName = poll
# Taste::RCMoperationKind = cyclic
# Taste::RCMperiod = 100 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["poll", "Ada", "Ada", "tcmanager", sp._fpgaConfigurations])
sp._language = "Ada"

# Interface "HandleTC"
sp = ast.ApLevelContainer("HandleTC")
ast.g_apLevelContainers["HandleTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::FwdCommand")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("route", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "FwdCommand"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("HandleTC", "route", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("HandleTC", "route", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::RawTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("packet", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RawTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("HandleTC", "packet", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("HandleTC", "packet", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = HandleTC
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["HandleTC", "Ada", "Ada", "tcmanager", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "Init"
sp = ast.ApLevelContainer("Init")
ast.g_apLevelContainers["Init"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Init
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Init", "Ada", "Ada", "tcmanager", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "NewEvAction"
sp = ast.ApLevelContainer("NewEvAction")
ast.g_apLevelContainers["NewEvAction"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::RxTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("accepted", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RxTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("NewEvAction", "accepted", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("NewEvAction", "accepted", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = NewEvAction
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["NewEvAction", "Ada", "Ada", "tcmanager", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "NewRxTC"
sp = ast.ApLevelContainer("NewRxTC")
ast.g_apLevelContainers["NewRxTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::Telecommand")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("tc", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "Telecommand"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("NewRxTC", "tc", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("NewRxTC", "tc", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::RxTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("accepted", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RxTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("NewRxTC", "accepted", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("NewRxTC", "accepted", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = NewRxTC
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["NewRxTC", "Ada", "Ada", "tcmanager", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "PollTC"
sp = ast.ApLevelContainer("PollTC")
ast.g_apLevelContainers["PollTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::RxTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("accepted", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RxTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("PollTC", "accepted", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("PollTC", "accepted", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = PollTC
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["PollTC", "Ada", "Ada", "tcmanager", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "Reboot"
sp = ast.ApLevelContainer("Reboot")
ast.g_apLevelContainers["Reboot"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Reboot
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Reboot", "Ada", "Ada", "tcmanager", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "SBKGTC"
sp = ast.ApLevelContainer("SBKGTC")
ast.g_apLevelContainers["SBKGTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::RawTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("packet", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RawTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("SBKGTC", "packet", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("SBKGTC", "packet", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Associated_Queue_Size = 1
# Taste::Communication_Layer = default
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = SBKGTC
# Taste::labelInheritance = true
# Taste::RCMoperationKind = sporadic
# Taste::RCMperiod = 0 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["SBKGTC", "Ada", "Ada", "tcmanager", sp._fpgaConfigurations])
sp._language = "Ada"


# Interface "SHKFDIRTC"
sp = ast.ApLevelContainer("SHKFDIRTC")
ast.g_apLevelContainers["SHKFDIRTC"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::RawTC")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("packet", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "RawTC"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("SHKFDIRTC", "packet", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("SHKFDIRTC", "packet", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Associated_Queue_Size = 1
# Taste::Communication_Layer = default
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = SHKFDIRTC
# Taste::labelInheritance = true
# Taste::RCMoperationKind = sporadic
# Taste::RCMperiod = 0 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["SHKFDIRTC", "Ada", "Ada", "tcmanager", sp._fpgaConfigurations])
sp._language = "Ada"

