/* Body file for function TCManager
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "tcmanager_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void tcmanager_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

extern void init_legacy(void);
extern unsigned legacy_initialized;
unsigned tcmanager_initialized = 0;
void init_tcmanager(void)
{
   if (0 == tcmanager_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused __attribute__((unused)) = getTimeInMilliseconds();
      tcmanager_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      extern void tcmanager_startup(void);
      tcmanager_startup();
      puts ("[TASTE] Initialization completed for function TCManager");
      tcmanager_initialized = 2;
   }
}
void tcmanager_SEvAction(void)
{
   sender_pid = tcmanager_sevaction_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: tcmanager,sevaction,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void tcmanager_PI_SEvAction(void);
   tcmanager_PI_SEvAction();
   // puts ("tcmanager_sevaction called");
   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *tcmanager_state(void);
      printf ("INNER_SDL_STATE: tcmanager,%s\n", tcmanager_state());
      fflush(stdout);
   }
}




void tcmanager_poll(void)
{
   sender_pid = tcmanager_poll_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: tcmanager,poll,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void tcmanager_PI_poll(void);
   tcmanager_PI_poll();
   // puts ("tcmanager_poll called");
   // trace the SDL state (appears on the MSC)
   if (1 == innerMsc) {
      extern char *tcmanager_state(void);
      printf ("INNER_SDL_STATE: tcmanager,%s\n", tcmanager_state());
      fflush(stdout);
   }
}

