/* Body file for function TCManager
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "tcmanager.h"
#include "asw_pus_rtems_5_0_leon3_st01_st17/asw/components/cctcmanager/src/cctcmanager_iface_v1.h"
//#include <stdio.h>


void tcmanager_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[TCManager] Startup");
}

void tcmanager_PI_SEvAction(void)
{
   // Write your code here
}


void tcmanager_PI_newTC
      (const asn1SccTelecommand *IN_tc)

{
   // Write your code here
}

void FInit(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    //cctcMng.EDROOMIRQ18Handler();
    //cctcMng.EDROOMIRQ18BottomHalfTask(something);
    edr.FInit();
}

void FGetTC(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    edr.FGetTC();
}

void FMngTCAcceptation(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    edr.FMngTCAcceptation();
}

void FMngTCRejection(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    edr.FMngTCRejection();
}

void FReboot(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    edr.FReboot();
}

void FTCExecCtrl(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    edr.FTCExecCtrl();
}

bool GAcceptTC(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.GAcceptTC();
}

bool GToReboot(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.GToReboot();
}

bool GFwdToHK_FDIR(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.GFwdToHK_FDIR();
}

bool GFwdToBKG(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.GFwdToBKG();
}

void FGetEvAction(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.FGetEvAction();
}

void FExecPrioTC(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.FExecPrioTC();
}

void FFwdHK_FDIRTC(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.FFwdHK_FDIRTC();
}

void FFwdBKGTC(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.FFwdBKGTC();
}

void FExecRebootTC(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.FExecRebootTC();
}

