/* Header file for function TCManager
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void tcmanager_startup(void);

/* Provided interfaces */
void tcmanager_PI_SEvAction( void );


void tcmanager_PI_newTC( const asn1SccTelecommand * );

/* Required interfaces */
extern void tcmanager_RI_SBKGTC( void );


extern void tcmanager_RI_SHKFDIRTC( void );


#ifdef __cplusplus
}
#endif
