--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (kazoo/templates/skeletons/ada-ri-source/function.tmplt)
with Sctre_Dataview;   use Sctre_Dataview;
with Taste_Basictypes; use Taste_Basictypes;
with System_Dataview;  use System_Dataview;
with adaasn1rtl;
with Interfaces.C.Strings; use Interfaces.C.Strings;
with System_Dataview; use System_Dataview;  --  contains definition of the PID type

package Tcmanager_RI is

   procedure Handletc (Route : out asn1SccFwdcommand; Packet : out asn1SccRawtc; Dest_PID : asn1sccPID := asn1sccEnv);
   
   
   procedure Init (Dest_PID : asn1SccPID := asn1sccEnv);
   
   
   procedure Newevaction (Accepted : out asn1SccRxtc; Dest_PID : asn1sccPID := asn1sccEnv);
   
   
   procedure Newrxtc (Tc : in out asn1SccTelecommand; Accepted : out asn1SccRxtc; Dest_PID : asn1sccPID := asn1sccEnv);
   
   
   procedure Polltc (Accepted : out asn1SccRxtc; Dest_PID : asn1sccPID := asn1sccEnv);
   
   
   procedure Reboot (Dest_PID : asn1SccPID := asn1sccEnv);
   
   
   procedure Sbkgtc (Packet : in out asn1SccRawtc; Dest_PID : asn1sccPID := asn1sccEnv);
   
   
   procedure Shkfdirtc (Packet : in out asn1SccRawtc; Dest_PID : asn1sccPID := asn1sccEnv);

   procedure Check_Queue (Res : out adaasn1rtl.Asn1Boolean)
      with Import, Convention => C, Link_Name => "tcmanager_check_queue";

   procedure Get_Sender (Sender : out asn1sccPID; Dest_PID : asn1SccPID := asn1sccEnv)
      with Import, Convention => C, Link_Name => "tcmanager_get_sender";

   procedure Get_Last_Error (Err : out asn1sccT_Runtime_Error; Dest_PID : asn1SccPID := asn1sccEnv)
      with Import, Convention => C, Link_Name => "tcmanager_get_last_error";

   --  Fixed number of instances: they cannot be deleted
   procedure Delete_Instance (unused_pid : asn1SccPID) is null;

   --  Return the SDL state as a char * for the MSC tracing function
   function To_C_Pointer (State_As_String : String) return Chars_Ptr is
      (New_String (State_As_String));
end Tcmanager_RI;
