/* Body file for function BKGTCExec
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "bkgtcexec.h"
#include "asw_pus_rtems_5_0_leon3/asw/components/cctcmanager/src/cctcmanager_iface_v1.h"
//#include <stdio.h>


void bkgtcexec_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[BKGTCExec] Startup");
}

void bkgtcexec_PI_SBKGTC(void)
{
   // Write your code here
}

void FExecBKGTC(){  //TODO
    CCTCManager::EDROOM_CTX_Top_0 edr;
    edr.FExecBKGTC();
}
