/* Header file for function BKGTCExec
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void bkgtcexec_startup(void);

/* Provided interfaces */
void bkgtcexec_PI_SBKGTC( void );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

