pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
pragma Warnings (Off, "no entities of ""Interfaces"" are referenced");
with Interfaces;
pragma Warnings (On, "no entities of ""Interfaces"" are referenced");

pragma Warnings (Off, "use clause for package ""Interfaces"" has no effect");
use Interfaces;
pragma Warnings (On, "use clause for package ""Interfaces"" has no effect");

with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");

pragma Warnings (Off, "no entities of ""System_Dataview"" are referenced");
pragma Warnings (Off, "use clause for package ""System_Dataview"" has no effect");
with System_Dataview; use System_Dataview;
pragma Warnings (On, "no entities of ""System_Dataview"" are referenced");
pragma Warnings (On, "use clause for package ""System_Dataview"" has no effect");

pragma Warnings (Off, "no entities of ""SCTRE_DATAVIEW"" are referenced");
pragma Warnings (Off, "use clause for package ""SCTRE_DATAVIEW"" has no effect");
with SCTRE_DATAVIEW; use SCTRE_DATAVIEW;
pragma Warnings (On, "no entities of ""SCTRE_DATAVIEW"" are referenced");
pragma Warnings (On, "use clause for package ""SCTRE_DATAVIEW"" has no effect");



package Hkfdirmng_Datamodel with SPARK_Mode
is


subtype asn1SccHkfdirmng_States_index_range is Integer range 0..0;
type asn1SccHkfdirmng_States is (asn1Sccready) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccHkfdirmng_States use
    (asn1Sccready => 0);

function asn1SccHkfdirmng_States_Equal(val1, val2 : asn1SccHkfdirmng_States) return Boolean;

ERR_HKFDIRMNG_STATES:constant Integer := 11; -- ready
function asn1SccHkfdirmng_States_IsConstraintValid(val : asn1SccHkfdirmng_States) return adaasn1rtl.ASN1_RESULT;

function asn1SccHkfdirmng_States_Init  return asn1SccHkfdirmng_States is
(asn1Sccready);
-- asn1SccHkfdirmng_Context --------------------------------------------

type asn1SccHkfdirmng_Context is record
    state : asn1SccHkfdirmng_States;
    init_done : adaasn1rtl.Asn1Boolean;
    sender : System_Dataview.asn1SccPID;
    offspring : System_Dataview.asn1SccPID;
    packet : SCTRE_DATAVIEW.asn1SccRawTC;
    time : SCTRE_DATAVIEW.asn1SccPr_time;
end record;


function asn1SccHkfdirmng_Context_Equal(val1, val2 : asn1SccHkfdirmng_Context) return Boolean;

ERR_HKFDIRMNG_CONTEXT:constant Integer := 271; -- 
ERR_HKFDIRMNG_CONTEXT_STATE_2:constant Integer := 221; -- 
ERR_HKFDIRMNG_CONTEXT_INIT_DONE:constant Integer := 226; -- 
ERR_HKFDIRMNG_CONTEXT_SENDER_2:constant Integer := 236; -- 
ERR_HKFDIRMNG_CONTEXT_OFFSPRING_2:constant Integer := 246; -- 
ERR_HKFDIRMNG_CONTEXT_PACKET_2:constant Integer := 256; -- 
ERR_HKFDIRMNG_CONTEXT_TIME_2:constant Integer := 266; -- 
function asn1SccHkfdirmng_Context_IsConstraintValid(val : asn1SccHkfdirmng_Context) return adaasn1rtl.ASN1_RESULT;

function asn1SccHkfdirmng_Context_Init  return asn1SccHkfdirmng_Context is
((state => asn1Sccready, init_done => False, sender => System_Dataview.asn1Sccbkgtcexec, offspring => System_Dataview.asn1Sccbkgtcexec, packet => (Length => 0, Data => (others => 0)), time => 0.0000000000000000000E+000));
subtype asn1SccHkfdirmng_T_Runtime_Error_Selection_index_range is Integer range 0..2;
type asn1SccHkfdirmng_T_Runtime_Error_Selection is (asn1Sccnoerror_present, asn1Sccencodeerror_present, asn1Sccdecodeerror_present) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccHkfdirmng_T_Runtime_Error_Selection use
    (asn1Sccnoerror_present => 1, asn1Sccencodeerror_present => 2, asn1Sccdecodeerror_present => 3);

function asn1SccHkfdirmng_T_Runtime_Error_Selection_Equal(val1, val2 : asn1SccHkfdirmng_T_Runtime_Error_Selection) return Boolean;

ERR_HKFDIRMNG_T_RUNTIME_ERROR_SELECTION:constant Integer := 16; -- noerror-present | encodeerror-present | decodeerror-present
function asn1SccHkfdirmng_T_Runtime_Error_Selection_IsConstraintValid(val : asn1SccHkfdirmng_T_Runtime_Error_Selection) return adaasn1rtl.ASN1_RESULT;

function asn1SccHkfdirmng_T_Runtime_Error_Selection_Init  return asn1SccHkfdirmng_T_Runtime_Error_Selection is
(asn1Sccnoerror_present);
pragma Warnings (Off, "there are no others");
pragma Warnings (On, "there are no others");
private
   --# hide Hkfdirmng_Datamodel;


end Hkfdirmng_Datamodel;