pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
pragma Warnings (Off, "no entities of ""Interfaces"" are referenced");
with Interfaces;
pragma Warnings (On, "no entities of ""Interfaces"" are referenced");

pragma Warnings (Off, "use clause for package ""Interfaces"" has no effect");
use Interfaces;
pragma Warnings (On, "use clause for package ""Interfaces"" has no effect");

with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");



package SCTRE_DATAVIEW with SPARK_Mode
is


subtype asn1SccRawTC_index is Integer range 1..256;
subtype asn1SccRawTC_array is adaasn1rtl.OctetBuffer(asn1SccRawTC_index);
subtype asn1SccRawTC_length_index is Integer range 0..256;
type asn1SccRawTC is  record
    Length : asn1SccRawTC_length_index;
    Data  : asn1SccRawTC_array;
end record;

function asn1SccRawTC_Equal(val1, val2 : asn1SccRawTC) return Boolean;

ERR_RAWTC:constant Integer := 31; -- (SIZE (0..256))
function asn1SccRawTC_IsConstraintValid(val : asn1SccRawTC) return adaasn1rtl.ASN1_RESULT;

function asn1SccRawTC_Init  return asn1SccRawTC is
((Length => 0, Data => (others => 0)));
subtype asn1SccRxTC_index_range is Integer range 0..1;
type asn1SccRxTC is (asn1Sccnot_accepted, asn1Sccaccepted) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccRxTC use
    (asn1Sccnot_accepted => 0, asn1Sccaccepted => 1);

function asn1SccRxTC_Equal(val1, val2 : asn1SccRxTC) return Boolean;

ERR_RXTC:constant Integer := 36; -- not-accepted | accepted
function asn1SccRxTC_IsConstraintValid(val : asn1SccRxTC) return adaasn1rtl.ASN1_RESULT;

function asn1SccRxTC_Init  return asn1SccRxTC is
(asn1Sccnot_accepted);
subtype asn1SccFwdCommand_index_range is Integer range 0..3;
type asn1SccFwdCommand is (asn1Sccto_reboot, asn1Sccexec_prio_tc, asn1Sccfwdhk_fdir_tc, asn1Sccfwdbkgtc) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccFwdCommand use
    (asn1Sccto_reboot => 0, asn1Sccexec_prio_tc => 1, asn1Sccfwdhk_fdir_tc => 2, asn1Sccfwdbkgtc => 3);

function asn1SccFwdCommand_Equal(val1, val2 : asn1SccFwdCommand) return Boolean;

ERR_FWDCOMMAND:constant Integer := 41; -- to-reboot | exec-prio-tc | fwdhk-fdir-tc | fwdbkgtc
function asn1SccFwdCommand_IsConstraintValid(val : asn1SccFwdCommand) return adaasn1rtl.ASN1_RESULT;

function asn1SccFwdCommand_Init  return asn1SccFwdCommand is
(asn1Sccto_reboot);
subtype asn1SccGPendingEvAction is adaasn1rtl.Asn1Boolean;


function asn1SccGPendingEvAction_Equal(val1, val2 : asn1SccGPendingEvAction) return Boolean;

ERR_GPENDINGEVACTION:constant Integer := 46; -- 
function asn1SccGPendingEvAction_IsConstraintValid(val : asn1SccGPendingEvAction) return adaasn1rtl.ASN1_RESULT;

function asn1SccGPendingEvAction_Init  return asn1SccGPendingEvAction is
(False);
subtype asn1SccGToReboot is adaasn1rtl.Asn1Boolean;


function asn1SccGToReboot_Equal(val1, val2 : asn1SccGToReboot) return Boolean;

ERR_GTOREBOOT:constant Integer := 51; -- 
function asn1SccGToReboot_IsConstraintValid(val : asn1SccGToReboot) return adaasn1rtl.ASN1_RESULT;

function asn1SccGToReboot_Init  return asn1SccGToReboot is
(False);
subtype asn1SccGFwToHK_FDIR is adaasn1rtl.Asn1Boolean;


function asn1SccGFwToHK_FDIR_Equal(val1, val2 : asn1SccGFwToHK_FDIR) return Boolean;

ERR_GFWTOHK_FDIR:constant Integer := 56; -- 
function asn1SccGFwToHK_FDIR_IsConstraintValid(val : asn1SccGFwToHK_FDIR) return adaasn1rtl.ASN1_RESULT;

function asn1SccGFwToHK_FDIR_Init  return asn1SccGFwToHK_FDIR is
(False);
subtype asn1SccGFwToBKG is adaasn1rtl.Asn1Boolean;


function asn1SccGFwToBKG_Equal(val1, val2 : asn1SccGFwToBKG) return Boolean;

ERR_GFWTOBKG:constant Integer := 61; -- 
function asn1SccGFwToBKG_IsConstraintValid(val : asn1SccGFwToBKG) return adaasn1rtl.ASN1_RESULT;

function asn1SccGFwToBKG_Init  return asn1SccGFwToBKG is
(False);
-- asn1SccTelecommand --------------------------------------------
subtype asn1SccTelecommand_service_type is adaasn1rtl.Asn1UInt range 0 .. 255;

subtype asn1SccTelecommand_subservice_type is adaasn1rtl.Asn1UInt range 0 .. 255;

subtype asn1SccTelecommand_param_index is Integer range 1..3;
subtype asn1SccTelecommand_param_array is adaasn1rtl.OctetBuffer(asn1SccTelecommand_param_index);
type asn1SccTelecommand_param is  record
    Data  : asn1SccTelecommand_param_array;
end record;

type asn1SccTelecommand is record
    service_type : asn1SccTelecommand_service_type;
    subservice_type : asn1SccTelecommand_subservice_type;
    param : asn1SccTelecommand_param;
end record;


function asn1SccTelecommand_service_type_Equal(val1, val2 : asn1SccTelecommand_service_type) return Boolean;

function asn1SccTelecommand_subservice_type_Equal(val1, val2 : asn1SccTelecommand_subservice_type) return Boolean;

function asn1SccTelecommand_param_Equal(val1, val2 : asn1SccTelecommand_param) return Boolean;

function asn1SccTelecommand_Equal(val1, val2 : asn1SccTelecommand) return Boolean;

ERR_TELECOMMAND_SERVICE_TYPE:constant Integer := 66; -- (0..255)
function asn1SccTelecommand_service_type_IsConstraintValid(val : asn1SccTelecommand_service_type) return adaasn1rtl.ASN1_RESULT;

ERR_TELECOMMAND_SUBSERVICE_TYPE:constant Integer := 71; -- (0..255)
function asn1SccTelecommand_subservice_type_IsConstraintValid(val : asn1SccTelecommand_subservice_type) return adaasn1rtl.ASN1_RESULT;

ERR_TELECOMMAND_PARAM:constant Integer := 76; -- (SIZE (3))
function asn1SccTelecommand_param_IsConstraintValid(val : asn1SccTelecommand_param) return adaasn1rtl.ASN1_RESULT;

ERR_TELECOMMAND:constant Integer := 81; -- 
function asn1SccTelecommand_IsConstraintValid(val : asn1SccTelecommand) return adaasn1rtl.ASN1_RESULT;

function asn1SccTelecommand_service_type_Init  return asn1SccTelecommand_service_type is
(0);
function asn1SccTelecommand_subservice_type_Init  return asn1SccTelecommand_subservice_type is
(0);
function asn1SccTelecommand_param_Init  return asn1SccTelecommand_param is
((Data => (others => 0)));
function asn1SccTelecommand_Init  return asn1SccTelecommand is
((service_type => 0, subservice_type => 0, param => (Data => (others => 0))));
subtype asn1SccPr_time is adaasn1rtl.Asn1Real;


function asn1SccPr_time_Equal(val1, val2 : asn1SccPr_time) return Boolean;

ERR_PR_TIME:constant Integer := 86; -- (0.0..1000000.0)
function asn1SccPr_time_IsConstraintValid(val : asn1SccPr_time) return adaasn1rtl.ASN1_RESULT;

function asn1SccPr_time_Init  return asn1SccPr_time is
(0.0000000000000000000E+000);
pragma Warnings (Off, "there are no others");
pragma Warnings (On, "there are no others");
private
   --# hide SCTRE_DATAVIEW;


end SCTRE_DATAVIEW;