pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool

pragma Warnings (Off, """String"" is already use-visible inside package ""Standard""");

pragma Warnings (Off, "redundant with clause in body");
pragma Warnings (On, "redundant with clause in body");

package body SCTRE_DATAVIEW with SPARK_Mode is


pragma Warnings (Off, "condition can only be False if invalid values present");
pragma Warnings (Off, "condition can only be True if invalid values present");


function asn1SccRawTC_Equal (val1, val2 :  asn1SccRawTC) return Boolean
is

begin
	return val1.Length = val2.Length and then val1.Data(1 .. val1.Length) = val2.Data(1 .. val2.Length);

end asn1SccRawTC_Equal;

function asn1SccRawTC_IsConstraintValid(val : asn1SccRawTC) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (val.Length <= 256);
    ret.ErrorCode := (if ret.Success then 0 else ERR_RAWTC);
    return ret;
end asn1SccRawTC_IsConstraintValid;





function asn1SccRxTC_Equal (val1, val2 :  asn1SccRxTC) return Boolean
is

begin
	return val1 = val2;

end asn1SccRxTC_Equal;

function asn1SccRxTC_IsConstraintValid(val : asn1SccRxTC) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (((val = asn1Sccnot_accepted)) OR ((val = asn1Sccaccepted)));
    ret.ErrorCode := (if ret.Success then 0 else ERR_RXTC);
    return ret;
end asn1SccRxTC_IsConstraintValid;





function asn1SccFwdCommand_Equal (val1, val2 :  asn1SccFwdCommand) return Boolean
is

begin
	return val1 = val2;

end asn1SccFwdCommand_Equal;

function asn1SccFwdCommand_IsConstraintValid(val : asn1SccFwdCommand) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (((((((val = asn1Sccto_reboot)) OR ((val = asn1Sccexec_prio_tc)))) OR ((val = asn1Sccfwdhk_fdir_tc)))) OR ((val = asn1Sccfwdbkgtc)));
    ret.ErrorCode := (if ret.Success then 0 else ERR_FWDCOMMAND);
    return ret;
end asn1SccFwdCommand_IsConstraintValid;





function asn1SccGPendingEvAction_Equal (val1, val2 :  asn1SccGPendingEvAction) return Boolean
is

begin
	return val1 = val2;

end asn1SccGPendingEvAction_Equal;

function asn1SccGPendingEvAction_IsConstraintValid(val : asn1SccGPendingEvAction) return adaasn1rtl.ASN1_RESULT
is
    pragma Unreferenced (val);
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    return ret;
end asn1SccGPendingEvAction_IsConstraintValid;





function asn1SccGToReboot_Equal (val1, val2 :  asn1SccGToReboot) return Boolean
is

begin
	return val1 = val2;

end asn1SccGToReboot_Equal;

function asn1SccGToReboot_IsConstraintValid(val : asn1SccGToReboot) return adaasn1rtl.ASN1_RESULT
is
    pragma Unreferenced (val);
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    return ret;
end asn1SccGToReboot_IsConstraintValid;





function asn1SccGFwToHK_FDIR_Equal (val1, val2 :  asn1SccGFwToHK_FDIR) return Boolean
is

begin
	return val1 = val2;

end asn1SccGFwToHK_FDIR_Equal;

function asn1SccGFwToHK_FDIR_IsConstraintValid(val : asn1SccGFwToHK_FDIR) return adaasn1rtl.ASN1_RESULT
is
    pragma Unreferenced (val);
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    return ret;
end asn1SccGFwToHK_FDIR_IsConstraintValid;





function asn1SccGFwToBKG_Equal (val1, val2 :  asn1SccGFwToBKG) return Boolean
is

begin
	return val1 = val2;

end asn1SccGFwToBKG_Equal;

function asn1SccGFwToBKG_IsConstraintValid(val : asn1SccGFwToBKG) return adaasn1rtl.ASN1_RESULT
is
    pragma Unreferenced (val);
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    return ret;
end asn1SccGFwToBKG_IsConstraintValid;





function asn1SccTelecommand_service_type_Equal (val1, val2 :  asn1SccTelecommand_service_type) return Boolean
is

begin
	return val1 = val2;

end asn1SccTelecommand_service_type_Equal;

function asn1SccTelecommand_subservice_type_Equal (val1, val2 :  asn1SccTelecommand_subservice_type) return Boolean
is

begin
	return val1 = val2;

end asn1SccTelecommand_subservice_type_Equal;

function asn1SccTelecommand_param_Equal (val1, val2 :  asn1SccTelecommand_param) return Boolean
is

begin
	return val1.Data = val2.Data;

end asn1SccTelecommand_param_Equal;

function asn1SccTelecommand_Equal (val1, val2 :  asn1SccTelecommand) return Boolean
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : Boolean := True;
    pragma Warnings (On, "initialization of ""ret"" has no effect");

begin
    ret := asn1SccTelecommand_service_type_Equal(val1.service_type, val2.service_type);

    if ret then
        ret := asn1SccTelecommand_subservice_type_Equal(val1.subservice_type, val2.subservice_type);

        if ret then
            ret := asn1SccTelecommand_param_Equal(val1.param, val2.param);

        end if;
    end if;
	return ret;

end asn1SccTelecommand_Equal;

function asn1SccTelecommand_service_type_IsConstraintValid(val : asn1SccTelecommand_service_type) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (val <= 255);
    ret.ErrorCode := (if ret.Success then 0 else ERR_TELECOMMAND_SERVICE_TYPE);
    return ret;
end asn1SccTelecommand_service_type_IsConstraintValid;

function asn1SccTelecommand_subservice_type_IsConstraintValid(val : asn1SccTelecommand_subservice_type) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (val <= 255);
    ret.ErrorCode := (if ret.Success then 0 else ERR_TELECOMMAND_SUBSERVICE_TYPE);
    return ret;
end asn1SccTelecommand_subservice_type_IsConstraintValid;

function asn1SccTelecommand_param_IsConstraintValid(val : asn1SccTelecommand_param) return adaasn1rtl.ASN1_RESULT
is
    pragma Unreferenced (val);
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    return ret;
end asn1SccTelecommand_param_IsConstraintValid;

function asn1SccTelecommand_IsConstraintValid(val : asn1SccTelecommand) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret := asn1SccTelecommand_service_type_IsConstraintValid(val.service_type);
    if ret.Success then
        ret := asn1SccTelecommand_subservice_type_IsConstraintValid(val.subservice_type);
        if ret.Success then
            ret := asn1SccTelecommand_param_IsConstraintValid(val.param);
        end if;
    end if;
    return ret;
end asn1SccTelecommand_IsConstraintValid;








function asn1SccPr_time_Equal (val1, val2 :  asn1SccPr_time) return Boolean
is

begin
	return adaasn1rtl.Asn1Real_Equal(val1, val2);

end asn1SccPr_time_Equal;

function asn1SccPr_time_IsConstraintValid(val : asn1SccPr_time) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := ((0.0000000000000000000E+000 <= val) AND (val <= 1.0000000000000000000E+006));
    ret.ErrorCode := (if ret.Success then 0 else ERR_PR_TIME);
    return ret;
end asn1SccPr_time_IsConstraintValid;




pragma Warnings (On, "condition can only be False if invalid values present");
pragma Warnings (On, "condition can only be True if invalid values present");

end SCTRE_DATAVIEW;