pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool

pragma Warnings (Off, """String"" is already use-visible inside package ""Standard""");

pragma Warnings (Off, "redundant with clause in body");
pragma Warnings (On, "redundant with clause in body");

package body System_Dataview with SPARK_Mode is


pragma Warnings (Off, "condition can only be False if invalid values present");
pragma Warnings (Off, "condition can only be True if invalid values present");


function asn1SccPID_Range_Equal (val1, val2 :  asn1SccPID_Range) return Boolean
is

begin
	return val1 = val2;

end asn1SccPID_Range_Equal;

function asn1SccPID_Range_IsConstraintValid(val : asn1SccPID_Range) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (val <= 4);
    ret.ErrorCode := (if ret.Success then 0 else ERR_PID_RANGE);
    return ret;
end asn1SccPID_Range_IsConstraintValid;





function asn1SccPID_Equal (val1, val2 :  asn1SccPID) return Boolean
is

begin
	return val1 = val2;

end asn1SccPID_Equal;

function asn1SccPID_IsConstraintValid(val : asn1SccPID) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (((((((((val = asn1Sccbkgtcexec)) OR ((val = asn1Scchkfdirmng)))) OR ((val = asn1Scclegacy)))) OR ((val = asn1Scctcmanager)))) OR ((val = asn1Sccenv)));
    ret.ErrorCode := (if ret.Success then 0 else ERR_PID);
    return ret;
end asn1SccPID_IsConstraintValid;




pragma Warnings (On, "condition can only be False if invalid values present");
pragma Warnings (On, "condition can only be True if invalid values present");

end System_Dataview;