pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
pragma Warnings (Off, "no entities of ""Interfaces"" are referenced");
with Interfaces;
pragma Warnings (On, "no entities of ""Interfaces"" are referenced");

pragma Warnings (Off, "use clause for package ""Interfaces"" has no effect");
use Interfaces;
pragma Warnings (On, "use clause for package ""Interfaces"" has no effect");

with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");



package TASTE_BasicTypes with SPARK_Mode
is


subtype asn1SccT_Int32 is adaasn1rtl.Asn1Int range -2147483648 .. 2147483647;


function asn1SccT_Int32_Equal(val1, val2 : asn1SccT_Int32) return Boolean;

ERR_T_INT32:constant Integer := 91; -- (-2147483648 .. 2147483647)
function asn1SccT_Int32_IsConstraintValid(val : asn1SccT_Int32) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_Int32_Init  return asn1SccT_Int32 is
(0);
subtype asn1SccT_UInt32 is adaasn1rtl.Asn1UInt range 0 .. 4294967295;


function asn1SccT_UInt32_Equal(val1, val2 : asn1SccT_UInt32) return Boolean;

ERR_T_UINT32:constant Integer := 96; -- (0 .. 4294967295)
function asn1SccT_UInt32_IsConstraintValid(val : asn1SccT_UInt32) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_UInt32_Init  return asn1SccT_UInt32 is
(0);
-- asn1SccT_Runtime_Error --------------------------------------------

subtype asn1SccT_Runtime_Error_index_range is Integer range 0..2;

type asn1SccT_Runtime_Error_selection is (noerror_PRESENT, encodeerror_PRESENT, decodeerror_PRESENT);
for asn1SccT_Runtime_Error_selection use
    (noerror_PRESENT => 1, encodeerror_PRESENT => 2, decodeerror_PRESENT => 3);
for asn1SccT_Runtime_Error_selection'Size use 32;

type asn1SccT_Runtime_Error(kind : asn1SccT_Runtime_Error_selection:= noerror_PRESENT) is
record
    case kind is
    when noerror_PRESENT =>
            noerror: asn1SccT_UInt32;
    when encodeerror_PRESENT =>
            encodeerror: asn1SccT_Int32;
    when decodeerror_PRESENT =>
            decodeerror: asn1SccT_Int32;
    end case;
end record;

for asn1SccT_Runtime_Error use
record
    kind at 0 range 0..31;
end record;

function asn1SccT_Runtime_Error_Equal(val1, val2 : asn1SccT_Runtime_Error) return Boolean;

ERR_T_RUNTIME_ERROR:constant Integer := 131; -- 
ERR_T_RUNTIME_ERROR_NOERROR_2:constant Integer := 106; -- 
ERR_T_RUNTIME_ERROR_ENCODEERROR_2:constant Integer := 116; -- 
ERR_T_RUNTIME_ERROR_DECODEERROR_2:constant Integer := 126; -- 
function asn1SccT_Runtime_Error_IsConstraintValid(val : asn1SccT_Runtime_Error) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_Runtime_Error_Init  return asn1SccT_Runtime_Error is
((kind => noerror_PRESENT, noerror => 0));
subtype asn1SccT_Int8 is adaasn1rtl.Asn1Int range -128 .. 127;


function asn1SccT_Int8_Equal(val1, val2 : asn1SccT_Int8) return Boolean;

ERR_T_INT8:constant Integer := 136; -- (-128 .. 127)
function asn1SccT_Int8_IsConstraintValid(val : asn1SccT_Int8) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_Int8_Init  return asn1SccT_Int8 is
(0);
subtype asn1SccT_UInt8 is adaasn1rtl.Asn1UInt range 0 .. 255;


function asn1SccT_UInt8_Equal(val1, val2 : asn1SccT_UInt8) return Boolean;

ERR_T_UINT8:constant Integer := 141; -- (0 .. 255)
function asn1SccT_UInt8_IsConstraintValid(val : asn1SccT_UInt8) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_UInt8_Init  return asn1SccT_UInt8 is
(0);
subtype asn1SccT_Boolean is adaasn1rtl.Asn1Boolean;


function asn1SccT_Boolean_Equal(val1, val2 : asn1SccT_Boolean) return Boolean;

ERR_T_BOOLEAN:constant Integer := 146; -- 
function asn1SccT_Boolean_IsConstraintValid(val : asn1SccT_Boolean) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_Boolean_Init  return asn1SccT_Boolean is
(False);
-- asn1SccT_Null_Record --------------------------------------------

type asn1SccT_Null_Record is record
    null;
end record;


function asn1SccT_Null_Record_Equal(val1, val2 : asn1SccT_Null_Record) return Boolean;

ERR_T_NULL_RECORD:constant Integer := 151; -- 
function asn1SccT_Null_Record_IsConstraintValid(val : asn1SccT_Null_Record) return adaasn1rtl.ASN1_RESULT;

function asn1SccT_Null_Record_Init  return asn1SccT_Null_Record is
((null record));
pragma Warnings (Off, "there are no others");
pragma Warnings (On, "there are no others");
private
   --# hide TASTE_BasicTypes;


end TASTE_BasicTypes;