pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
pragma Warnings (Off, "no entities of ""Interfaces"" are referenced");
with Interfaces;
pragma Warnings (On, "no entities of ""Interfaces"" are referenced");

pragma Warnings (Off, "use clause for package ""Interfaces"" has no effect");
use Interfaces;
pragma Warnings (On, "use clause for package ""Interfaces"" has no effect");

with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");

pragma Warnings (Off, "no entities of ""System_Dataview"" are referenced");
pragma Warnings (Off, "use clause for package ""System_Dataview"" has no effect");
with System_Dataview; use System_Dataview;
pragma Warnings (On, "no entities of ""System_Dataview"" are referenced");
pragma Warnings (On, "use clause for package ""System_Dataview"" has no effect");

pragma Warnings (Off, "no entities of ""SCTRE_DATAVIEW"" are referenced");
pragma Warnings (Off, "use clause for package ""SCTRE_DATAVIEW"" has no effect");
with SCTRE_DATAVIEW; use SCTRE_DATAVIEW;
pragma Warnings (On, "no entities of ""SCTRE_DATAVIEW"" are referenced");
pragma Warnings (On, "use clause for package ""SCTRE_DATAVIEW"" has no effect");



package Tcmanager_Datamodel with SPARK_Mode
is


subtype asn1SccTcmanager_States_index_range is Integer range 0..2;
type asn1SccTcmanager_States is (asn1Sccvalidtc, asn1Sccready, asn1Sccreboot) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccTcmanager_States use
    (asn1Sccvalidtc => 0, asn1Sccready => 1, asn1Sccreboot => 2);

function asn1SccTcmanager_States_Equal(val1, val2 : asn1SccTcmanager_States) return Boolean;

ERR_TCMANAGER_STATES:constant Integer := 21; -- validtc | ready | reboot
function asn1SccTcmanager_States_IsConstraintValid(val : asn1SccTcmanager_States) return adaasn1rtl.ASN1_RESULT;

function asn1SccTcmanager_States_Init  return asn1SccTcmanager_States is
(asn1Sccvalidtc);
-- asn1SccTcmanager_Context --------------------------------------------

type asn1SccTcmanager_Context is record
    state : asn1SccTcmanager_States;
    init_done : adaasn1rtl.Asn1Boolean;
    sender : System_Dataview.asn1SccPID;
    offspring : System_Dataview.asn1SccPID;
    acceptance : SCTRE_DATAVIEW.asn1SccRxTC;
    packet : SCTRE_DATAVIEW.asn1SccRawTC;
    fwdcomm : SCTRE_DATAVIEW.asn1SccFwdCommand;
    tc : SCTRE_DATAVIEW.asn1SccTelecommand;
end record;


function asn1SccTcmanager_Context_Equal(val1, val2 : asn1SccTcmanager_Context) return Boolean;

ERR_TCMANAGER_CONTEXT:constant Integer := 346; -- 
ERR_TCMANAGER_CONTEXT_STATE_2:constant Integer := 281; -- 
ERR_TCMANAGER_CONTEXT_INIT_DONE:constant Integer := 286; -- 
ERR_TCMANAGER_CONTEXT_SENDER_2:constant Integer := 296; -- 
ERR_TCMANAGER_CONTEXT_OFFSPRING_2:constant Integer := 306; -- 
ERR_TCMANAGER_CONTEXT_ACCEPTANCE_2:constant Integer := 316; -- 
ERR_TCMANAGER_CONTEXT_PACKET_2:constant Integer := 326; -- 
ERR_TCMANAGER_CONTEXT_FWDCOMM_2:constant Integer := 336; -- 
ERR_TCMANAGER_CONTEXT_TC:constant Integer := 341; -- 
function asn1SccTcmanager_Context_IsConstraintValid(val : asn1SccTcmanager_Context) return adaasn1rtl.ASN1_RESULT;

function asn1SccTcmanager_Context_Init  return asn1SccTcmanager_Context is
((state => asn1Sccvalidtc, init_done => False, sender => System_Dataview.asn1Sccbkgtcexec, offspring => System_Dataview.asn1Sccbkgtcexec, acceptance => SCTRE_DATAVIEW.asn1Sccnot_accepted, packet => (Length => 0, Data => (others => 0)), fwdcomm => SCTRE_DATAVIEW.asn1Sccto_reboot, tc => SCTRE_DATAVIEW.asn1SccTelecommand_Init));
subtype asn1SccTcmanager_T_Runtime_Error_Selection_index_range is Integer range 0..2;
type asn1SccTcmanager_T_Runtime_Error_Selection is (asn1Sccnoerror_present, asn1Sccencodeerror_present, asn1Sccdecodeerror_present) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccTcmanager_T_Runtime_Error_Selection use
    (asn1Sccnoerror_present => 1, asn1Sccencodeerror_present => 2, asn1Sccdecodeerror_present => 3);

function asn1SccTcmanager_T_Runtime_Error_Selection_Equal(val1, val2 : asn1SccTcmanager_T_Runtime_Error_Selection) return Boolean;

ERR_TCMANAGER_T_RUNTIME_ERROR_SELECTION:constant Integer := 26; -- noerror-present | encodeerror-present | decodeerror-present
function asn1SccTcmanager_T_Runtime_Error_Selection_IsConstraintValid(val : asn1SccTcmanager_T_Runtime_Error_Selection) return adaasn1rtl.ASN1_RESULT;

function asn1SccTcmanager_T_Runtime_Error_Selection_Init  return asn1SccTcmanager_T_Runtime_Error_Selection is
(asn1Sccnoerror_present);
pragma Warnings (Off, "there are no others");
pragma Warnings (On, "there are no others");
private
   --# hide Tcmanager_Datamodel;


end Tcmanager_Datamodel;