pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool

pragma Warnings (Off, """String"" is already use-visible inside package ""Standard""");

pragma Warnings (Off, "redundant with clause in body");

pragma Warnings (Off, "no entities of ""System_Dataview"" are referenced");
pragma Warnings (Off, "use clause for package ""System_Dataview"" has no effect");
pragma Warnings (Off, "unit ""System_Dataview"" is not referenced");
with System_Dataview;
pragma Warnings (On, "no entities of ""System_Dataview"" are referenced");
pragma Warnings (On, "use clause for package ""System_Dataview"" has no effect");
pragma Warnings (On, "unit ""System_Dataview"" is not referenced");


pragma Warnings (Off, "no entities of ""SCTRE_DATAVIEW"" are referenced");
pragma Warnings (Off, "use clause for package ""SCTRE_DATAVIEW"" has no effect");
pragma Warnings (Off, "unit ""SCTRE_DATAVIEW"" is not referenced");
with SCTRE_DATAVIEW;
pragma Warnings (On, "no entities of ""SCTRE_DATAVIEW"" are referenced");
pragma Warnings (On, "use clause for package ""SCTRE_DATAVIEW"" has no effect");
pragma Warnings (On, "unit ""SCTRE_DATAVIEW"" is not referenced");

pragma Warnings (On, "redundant with clause in body");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible");
use type System_Dataview.asn1SccPID;
use type SCTRE_DATAVIEW.asn1SccRxTC;
use type SCTRE_DATAVIEW.asn1SccRawTC;
use type SCTRE_DATAVIEW.asn1SccFwdCommand;
use type SCTRE_DATAVIEW.asn1SccTelecommand_service_type;
use type SCTRE_DATAVIEW.asn1SccTelecommand_subservice_type;
use type SCTRE_DATAVIEW.asn1SccTelecommand_param;
use type SCTRE_DATAVIEW.asn1SccTelecommand;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible");
package body Tcmanager_Datamodel with SPARK_Mode is


pragma Warnings (Off, "condition can only be False if invalid values present");
pragma Warnings (Off, "condition can only be True if invalid values present");


function asn1SccTcmanager_States_Equal (val1, val2 :  asn1SccTcmanager_States) return Boolean
is

begin
	return val1 = val2;

end asn1SccTcmanager_States_Equal;

function asn1SccTcmanager_States_IsConstraintValid(val : asn1SccTcmanager_States) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (((((val = asn1Sccvalidtc)) OR ((val = asn1Sccready)))) OR ((val = asn1Sccreboot)));
    ret.ErrorCode := (if ret.Success then 0 else ERR_TCMANAGER_STATES);
    return ret;
end asn1SccTcmanager_States_IsConstraintValid;





function asn1SccTcmanager_Context_Equal (val1, val2 :  asn1SccTcmanager_Context) return Boolean
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : Boolean := True;
    pragma Warnings (On, "initialization of ""ret"" has no effect");

begin
    ret := (val1.state = val2.state);

    if ret then
        ret := (val1.init_done = val2.init_done);

        if ret then
            ret := (val1.sender = val2.sender);

            if ret then
                ret := (val1.offspring = val2.offspring);

                if ret then
                    ret := (val1.acceptance = val2.acceptance);

                    if ret then
                        ret := SCTRE_DATAVIEW.asn1SccRawTC_Equal(val1.packet, val2.packet);

                        if ret then
                            ret := (val1.fwdcomm = val2.fwdcomm);

                            if ret then
                                ret := SCTRE_DATAVIEW.asn1SccTelecommand_Equal(val1.tc, val2.tc);

                            end if;
                        end if;
                    end if;
                end if;
            end if;
        end if;
    end if;
	return ret;

end asn1SccTcmanager_Context_Equal;

function asn1SccTcmanager_Context_IsConstraintValid(val : asn1SccTcmanager_Context) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret := asn1SccTcmanager_States_IsConstraintValid(val.state);
    if ret.Success then
        ret := System_Dataview.asn1SccPID_IsConstraintValid(val.sender);
        if ret.Success then
            ret := System_Dataview.asn1SccPID_IsConstraintValid(val.offspring);
            if ret.Success then
                ret := SCTRE_DATAVIEW.asn1SccRxTC_IsConstraintValid(val.acceptance);
                if ret.Success then
                    ret := SCTRE_DATAVIEW.asn1SccRawTC_IsConstraintValid(val.packet);
                    if ret.Success then
                        ret := SCTRE_DATAVIEW.asn1SccFwdCommand_IsConstraintValid(val.fwdcomm);
                        if ret.Success then
                            ret := SCTRE_DATAVIEW.asn1SccTelecommand_IsConstraintValid(val.tc);
                        end if;
                    end if;
                end if;
            end if;
        end if;
    end if;
    return ret;
end asn1SccTcmanager_Context_IsConstraintValid;





function asn1SccTcmanager_T_Runtime_Error_Selection_Equal (val1, val2 :  asn1SccTcmanager_T_Runtime_Error_Selection) return Boolean
is

begin
	return val1 = val2;

end asn1SccTcmanager_T_Runtime_Error_Selection_Equal;

function asn1SccTcmanager_T_Runtime_Error_Selection_IsConstraintValid(val : asn1SccTcmanager_T_Runtime_Error_Selection) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (((((val = asn1Sccnoerror_present)) OR ((val = asn1Sccencodeerror_present)))) OR ((val = asn1Sccdecodeerror_present)));
    ret.ErrorCode := (if ret.Success then 0 else ERR_TCMANAGER_T_RUNTIME_ERROR_SELECTION);
    return ret;
end asn1SccTcmanager_T_Runtime_Error_Selection_IsConstraintValid;




pragma Warnings (On, "condition can only be False if invalid values present");
pragma Warnings (On, "condition can only be True if invalid values present");

end Tcmanager_Datamodel;