#!/usr/bin/env python3

# File generated by asn2aadlPlus: DO NOT EDIT
from dmt.commonPy import aadlAST as ast

ast.g_signals = dict()

s = ast.Signal("dataview/dataview-uniq.asn", "FwdCommand", 8)
ast.g_signals["FwdCommand"] = s
ast.g_signals["DataView::FwdCommand"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "GFwToBKG", 8)
ast.g_signals["GFwToBKG"] = s
ast.g_signals["DataView::GFwToBKG"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "GFwToHK-FDIR", 8)
ast.g_signals["GFwToHK_FDIR"] = s
ast.g_signals["DataView::GFwToHK_FDIR"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "GPendingEvAction", 8)
ast.g_signals["GPendingEvAction"] = s
ast.g_signals["DataView::GPendingEvAction"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "GToReboot", 8)
ast.g_signals["GToReboot"] = s
ast.g_signals["DataView::GToReboot"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "PID", 8)
ast.g_signals["PID"] = s
ast.g_signals["DataView::PID"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "PID-Range", 8)
ast.g_signals["PID_Range"] = s
ast.g_signals["DataView::PID_Range"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "Pr-time", 16)
ast.g_signals["Pr_time"] = s
ast.g_signals["DataView::Pr_time"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "RawTC", 264)
ast.g_signals["RawTC"] = s
ast.g_signals["DataView::RawTC"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "RxTC", 8)
ast.g_signals["RxTC"] = s
ast.g_signals["DataView::RxTC"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-Boolean", 8)
ast.g_signals["T_Boolean"] = s
ast.g_signals["DataView::T_Boolean"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-Int32", 8)
ast.g_signals["T_Int32"] = s
ast.g_signals["DataView::T_Int32"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-Int8", 8)
ast.g_signals["T_Int8"] = s
ast.g_signals["DataView::T_Int8"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-Null-Record", 0)
ast.g_signals["T_Null_Record"] = s
ast.g_signals["DataView::T_Null_Record"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-Runtime-Error", 16)
ast.g_signals["T_Runtime_Error"] = s
ast.g_signals["DataView::T_Runtime_Error"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-UInt32", 8)
ast.g_signals["T_UInt32"] = s
ast.g_signals["DataView::T_UInt32"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "T-UInt8", 8)
ast.g_signals["T_UInt8"] = s
ast.g_signals["DataView::T_UInt8"] = s
s = ast.Signal("dataview/dataview-uniq.asn", "Telecommand", 24)
ast.g_signals["Telecommand"] = s
ast.g_signals["DataView::Telecommand"] = s
