/* Body file for function HKFDIRMng
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "hkfdirmng_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void hkfdirmng_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned hkfdirmng_initialized = 0;
void init_hkfdirmng(void)
{
   if (0 == hkfdirmng_initialized) {
      hkfdirmng_initialized = 1;
      // Call user code startup function
      extern void hkfdirmng_startup(void);
      hkfdirmng_startup();
      puts ("[TASTE] Initialization completed for function HKFDIRMng");
      hkfdirmng_initialized = 2;
   }
}
void hkfdirmng_SHKFDIRTC(void)
{
   sender_pid = hkfdirmng_shkfdirtc_get_sender();

   //  Directly call user code, no parameters to pass
   extern void hkfdirmng_PI_SHKFDIRTC(void);
   hkfdirmng_PI_SHKFDIRTC();
   // puts ("hkfdirmng_shkfdirtc called");
}




void hkfdirmng_trigger(void)
{
   sender_pid = hkfdirmng_trigger_get_sender();

   //  Directly call user code, no parameters to pass
   extern void hkfdirmng_PI_trigger(void);
   hkfdirmng_PI_trigger();
   // puts ("hkfdirmng_trigger called");
}

