/* Header file for function HKFDIRMng
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void hkfdirmng_startup(void);

/* Provided interfaces */
void hkfdirmng_PI_SHKFDIRTC( void );


void hkfdirmng_PI_trigger( void );

/* Required interfaces */
extern void hkfdirmng_RI_SEvAction( void );


#ifdef __cplusplus
}
#endif
