/* Body file for function HKFDIRMng
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "hkfdirmng.h"
//#include "asw_pus_rtems_5_0_leon3/asw/components/cctcmanager/src/cctcmanager_iface_v1.h"
#include "/home/jorge/sctre/work/asw_pus_rtems_5_0_leon3/asw/components/cctcmanager/src/cctcmanager_iface_v1.h"
//#include "/../../../../../asw_pus_rtems_5_0_leon3/asw/components/cctcmanager/src/cctcmanager_iface_v1.h"
//#include <stdio.h>


void hkfdirmng_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[HKFDIRMng] Startup");
}

void hkfdirmng_PI_SHKFDIRTC(void)
{
   // Write your code here
}


void hkfdirmng_PI_trigger(void)
{
   // Write your code here
}


void FInitHK_FDIR(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    edr.FInitHK_FDIR();
}

void FDoHK_FDIR(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    edr.FDoHK_FDIR();
}

void FExecHK_FDIR_TC(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    edr.FExecHK_FDIR_TC();
}

bool GPendingEvAction(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.GPendingEvAction();
}

void FFwdEvAction(){
    CCTCManager::EDROOM_CTX_Top_0 edr;
    return edr.FFwdEvAction();
}
