/* Header file for function Legacy
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void legacy_startup(void);

/* Provided interfaces */
void legacy_PI_DoHousekeeping( );


void legacy_PI_ExecBKGTC( const asn1SccRawTC * );


void legacy_PI_ExecHKFDIRTC( const asn1SccRawTC * );


void legacy_PI_HandleTC( asn1SccFwdCommand *, asn1SccRawTC * );


void legacy_PI_Init( );


void legacy_PI_NewEvAction( asn1SccRxTC * );


void legacy_PI_NewRxTC( const asn1SccTelecommand *, asn1SccRxTC * );


void legacy_PI_PollTC( asn1SccRxTC * );


void legacy_PI_Reboot( );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

