#ifndef GENERATED_ASN1SCC_dataview_uniq_H
#define GENERATED_ASN1SCC_dataview_uniq_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef struct {
    int nCount;
    byte arr[256];
} asn1SccRawTC;


flag asn1SccRawTC_Equal(const asn1SccRawTC* pVal1, const asn1SccRawTC* pVal2);

#define ERR_RAWTC		1  /*(SIZE (0..256))*/
flag asn1SccRawTC_IsConstraintValid(const asn1SccRawTC* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccRawTC asn1SccRawTC_constant;
#else
#define asn1SccRawTC_constant {.nCount = 0, .arr  = {[0 ... 256-1] = 0 }}
#endif

void asn1SccRawTC_Initialize(asn1SccRawTC* pVal);

#define ERR_UPER_ENCODE_RAWTC		2  /**/
#define asn1SccRawTC_REQUIRED_BYTES_FOR_ENCODING       258
#define asn1SccRawTC_REQUIRED_BITS_FOR_ENCODING        2057

flag asn1SccRawTC_Encode(const asn1SccRawTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_RAWTC		3  /**/
flag asn1SccRawTC_Decode(asn1SccRawTC* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccRawTC_REQUIRED_BYTES_FOR_ACN_ENCODING       258
#define asn1SccRawTC_REQUIRED_BITS_FOR_ACN_ENCODING        2057

#define ERR_ACN_ENCODE_RAWTC		4  /**/

flag asn1SccRawTC_ACN_Encode(const asn1SccRawTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_RAWTC		5  /**/
flag asn1SccRawTC_ACN_Decode(asn1SccRawTC* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    RxTC_not_accepted = 0,
    RxTC_accepted = 1
} asn1SccRxTC;

// please use the following macros to avoid breaking code.
#define asn1SccRxTC_not_accepted RxTC_not_accepted
#define asn1SccRxTC_accepted RxTC_accepted

flag asn1SccRxTC_Equal(const asn1SccRxTC* pVal1, const asn1SccRxTC* pVal2);

#define ERR_RXTC		6  /*not-accepted | accepted*/
flag asn1SccRxTC_IsConstraintValid(const asn1SccRxTC* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccRxTC asn1SccRxTC_constant;
#else
#define asn1SccRxTC_constant RxTC_not_accepted
#endif

void asn1SccRxTC_Initialize(asn1SccRxTC* pVal);

#define ERR_UPER_ENCODE_RXTC		7  /**/
#define asn1SccRxTC_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccRxTC_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccRxTC_Encode(const asn1SccRxTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_RXTC		8  /**/
flag asn1SccRxTC_Decode(asn1SccRxTC* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccRxTC_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccRxTC_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_RXTC		9  /**/

flag asn1SccRxTC_ACN_Encode(const asn1SccRxTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_RXTC		10  /**/
flag asn1SccRxTC_ACN_Decode(asn1SccRxTC* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    FwdCommand_to_reboot = 0,
    FwdCommand_exec_prio_tc = 1,
    FwdCommand_fwdhk_fdir_tc = 2,
    FwdCommand_fwdbkgtc = 3
} asn1SccFwdCommand;

// please use the following macros to avoid breaking code.
#define asn1SccFwdCommand_to_reboot FwdCommand_to_reboot
#define asn1SccFwdCommand_exec_prio_tc FwdCommand_exec_prio_tc
#define asn1SccFwdCommand_fwdhk_fdir_tc FwdCommand_fwdhk_fdir_tc
#define asn1SccFwdCommand_fwdbkgtc FwdCommand_fwdbkgtc

flag asn1SccFwdCommand_Equal(const asn1SccFwdCommand* pVal1, const asn1SccFwdCommand* pVal2);

#define ERR_FWDCOMMAND		11  /*to-reboot | exec-prio-tc | fwdhk-fdir-tc | fwdbkgtc*/
flag asn1SccFwdCommand_IsConstraintValid(const asn1SccFwdCommand* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccFwdCommand asn1SccFwdCommand_constant;
#else
#define asn1SccFwdCommand_constant FwdCommand_to_reboot
#endif

void asn1SccFwdCommand_Initialize(asn1SccFwdCommand* pVal);

#define ERR_UPER_ENCODE_FWDCOMMAND		12  /**/
#define asn1SccFwdCommand_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccFwdCommand_REQUIRED_BITS_FOR_ENCODING        2

flag asn1SccFwdCommand_Encode(const asn1SccFwdCommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_FWDCOMMAND		13  /**/
flag asn1SccFwdCommand_Decode(asn1SccFwdCommand* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccFwdCommand_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccFwdCommand_REQUIRED_BITS_FOR_ACN_ENCODING        2

#define ERR_ACN_ENCODE_FWDCOMMAND		14  /**/

flag asn1SccFwdCommand_ACN_Encode(const asn1SccFwdCommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_FWDCOMMAND		15  /**/
flag asn1SccFwdCommand_ACN_Decode(asn1SccFwdCommand* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccGPendingEvAction;


flag asn1SccGPendingEvAction_Equal(const asn1SccGPendingEvAction* pVal1, const asn1SccGPendingEvAction* pVal2);

#define ERR_GPENDINGEVACTION		16  /**/
flag asn1SccGPendingEvAction_IsConstraintValid(const asn1SccGPendingEvAction* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccGPendingEvAction asn1SccGPendingEvAction_constant;
#else
#define asn1SccGPendingEvAction_constant FALSE
#endif

void asn1SccGPendingEvAction_Initialize(asn1SccGPendingEvAction* pVal);

#define ERR_UPER_ENCODE_GPENDINGEVACTION		17  /**/
#define asn1SccGPendingEvAction_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccGPendingEvAction_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccGPendingEvAction_Encode(const asn1SccGPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GPENDINGEVACTION		18  /**/
flag asn1SccGPendingEvAction_Decode(asn1SccGPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccGPendingEvAction_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccGPendingEvAction_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_GPENDINGEVACTION		19  /**/

flag asn1SccGPendingEvAction_ACN_Encode(const asn1SccGPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GPENDINGEVACTION		20  /**/
flag asn1SccGPendingEvAction_ACN_Decode(asn1SccGPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccGToReboot;


flag asn1SccGToReboot_Equal(const asn1SccGToReboot* pVal1, const asn1SccGToReboot* pVal2);

#define ERR_GTOREBOOT		21  /**/
flag asn1SccGToReboot_IsConstraintValid(const asn1SccGToReboot* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccGToReboot asn1SccGToReboot_constant;
#else
#define asn1SccGToReboot_constant FALSE
#endif

void asn1SccGToReboot_Initialize(asn1SccGToReboot* pVal);

#define ERR_UPER_ENCODE_GTOREBOOT		22  /**/
#define asn1SccGToReboot_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccGToReboot_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccGToReboot_Encode(const asn1SccGToReboot* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GTOREBOOT		23  /**/
flag asn1SccGToReboot_Decode(asn1SccGToReboot* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccGToReboot_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccGToReboot_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_GTOREBOOT		24  /**/

flag asn1SccGToReboot_ACN_Encode(const asn1SccGToReboot* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GTOREBOOT		25  /**/
flag asn1SccGToReboot_ACN_Decode(asn1SccGToReboot* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccGFwToHK_FDIR;


flag asn1SccGFwToHK_FDIR_Equal(const asn1SccGFwToHK_FDIR* pVal1, const asn1SccGFwToHK_FDIR* pVal2);

#define ERR_GFWTOHK_FDIR		26  /**/
flag asn1SccGFwToHK_FDIR_IsConstraintValid(const asn1SccGFwToHK_FDIR* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccGFwToHK_FDIR asn1SccGFwToHK_FDIR_constant;
#else
#define asn1SccGFwToHK_FDIR_constant FALSE
#endif

void asn1SccGFwToHK_FDIR_Initialize(asn1SccGFwToHK_FDIR* pVal);

#define ERR_UPER_ENCODE_GFWTOHK_FDIR		27  /**/
#define asn1SccGFwToHK_FDIR_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccGFwToHK_FDIR_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccGFwToHK_FDIR_Encode(const asn1SccGFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GFWTOHK_FDIR		28  /**/
flag asn1SccGFwToHK_FDIR_Decode(asn1SccGFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccGFwToHK_FDIR_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccGFwToHK_FDIR_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_GFWTOHK_FDIR		29  /**/

flag asn1SccGFwToHK_FDIR_ACN_Encode(const asn1SccGFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GFWTOHK_FDIR		30  /**/
flag asn1SccGFwToHK_FDIR_ACN_Decode(asn1SccGFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccGFwToBKG;


flag asn1SccGFwToBKG_Equal(const asn1SccGFwToBKG* pVal1, const asn1SccGFwToBKG* pVal2);

#define ERR_GFWTOBKG		31  /**/
flag asn1SccGFwToBKG_IsConstraintValid(const asn1SccGFwToBKG* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccGFwToBKG asn1SccGFwToBKG_constant;
#else
#define asn1SccGFwToBKG_constant FALSE
#endif

void asn1SccGFwToBKG_Initialize(asn1SccGFwToBKG* pVal);

#define ERR_UPER_ENCODE_GFWTOBKG		32  /**/
#define asn1SccGFwToBKG_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccGFwToBKG_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccGFwToBKG_Encode(const asn1SccGFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GFWTOBKG		33  /**/
flag asn1SccGFwToBKG_Decode(asn1SccGFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccGFwToBKG_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccGFwToBKG_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_GFWTOBKG		34  /**/

flag asn1SccGFwToBKG_ACN_Encode(const asn1SccGFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GFWTOBKG		35  /**/
flag asn1SccGFwToBKG_ACN_Decode(asn1SccGFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccTelecommand --------------------------------------------*/
typedef asn1SccUint asn1SccTelecommand_service_type;

typedef asn1SccUint asn1SccTelecommand_subservice_type;

typedef struct {
    byte arr[3];
} asn1SccTelecommand_param;

typedef struct {
    asn1SccTelecommand_service_type service_type;
    asn1SccTelecommand_subservice_type subservice_type;
    asn1SccTelecommand_param param;

} asn1SccTelecommand;

flag asn1SccTelecommand_service_type_Equal(const asn1SccTelecommand_service_type* pVal1, const asn1SccTelecommand_service_type* pVal2);

flag asn1SccTelecommand_subservice_type_Equal(const asn1SccTelecommand_subservice_type* pVal1, const asn1SccTelecommand_subservice_type* pVal2);

flag asn1SccTelecommand_param_Equal(const asn1SccTelecommand_param* pVal1, const asn1SccTelecommand_param* pVal2);

flag asn1SccTelecommand_Equal(const asn1SccTelecommand* pVal1, const asn1SccTelecommand* pVal2);

#define ERR_TELECOMMAND_SERVICE_TYPE		36  /*(0..255)*/
flag asn1SccTelecommand_service_type_IsConstraintValid(const asn1SccTelecommand_service_type* pVal, int* pErrCode);

#define ERR_TELECOMMAND_SUBSERVICE_TYPE		41  /*(0..255)*/
flag asn1SccTelecommand_subservice_type_IsConstraintValid(const asn1SccTelecommand_subservice_type* pVal, int* pErrCode);

#define ERR_TELECOMMAND_PARAM		46  /*(SIZE (3))*/
flag asn1SccTelecommand_param_IsConstraintValid(const asn1SccTelecommand_param* pVal, int* pErrCode);

#define ERR_TELECOMMAND		51  /**/
flag asn1SccTelecommand_IsConstraintValid(const asn1SccTelecommand* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccTelecommand_service_type asn1SccTelecommand_service_type_constant;
#else
#define asn1SccTelecommand_service_type_constant 0UL
#endif
#ifdef __cplusplus
extern const asn1SccTelecommand_subservice_type asn1SccTelecommand_subservice_type_constant;
#else
#define asn1SccTelecommand_subservice_type_constant 0UL
#endif
#ifdef __cplusplus
extern const asn1SccTelecommand_param asn1SccTelecommand_param_constant;
#else
#define asn1SccTelecommand_param_constant {.arr  = {[0 ... 3-1] = 0 }}
#endif
#ifdef __cplusplus
extern const asn1SccTelecommand asn1SccTelecommand_constant;
#else
#define asn1SccTelecommand_constant {.service_type = 0UL, .subservice_type = 0UL, .param = {.arr  = {[0 ... 3-1] = 0 }}}
#endif

void asn1SccTelecommand_Initialize(asn1SccTelecommand* pVal);

#define ERR_UPER_ENCODE_TELECOMMAND		52  /**/
#define ERR_UPER_ENCODE_TELECOMMAND_SERVICE_TYPE		37  /**/
#define ERR_UPER_ENCODE_TELECOMMAND_SUBSERVICE_TYPE		42  /**/
#define ERR_UPER_ENCODE_TELECOMMAND_PARAM		47  /**/
#define asn1SccTelecommand_REQUIRED_BYTES_FOR_ENCODING       5
#define asn1SccTelecommand_REQUIRED_BITS_FOR_ENCODING        40

flag asn1SccTelecommand_Encode(const asn1SccTelecommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_TELECOMMAND		53  /**/
#define ERR_UPER_DECODE_TELECOMMAND_SERVICE_TYPE		38  /**/
#define ERR_UPER_DECODE_TELECOMMAND_SUBSERVICE_TYPE		43  /**/
#define ERR_UPER_DECODE_TELECOMMAND_PARAM		48  /**/
flag asn1SccTelecommand_Decode(asn1SccTelecommand* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccTelecommand_REQUIRED_BYTES_FOR_ACN_ENCODING       5
#define asn1SccTelecommand_REQUIRED_BITS_FOR_ACN_ENCODING        40

#define ERR_ACN_ENCODE_TELECOMMAND		54  /**/
#define ERR_ACN_ENCODE_TELECOMMAND_SERVICE_TYPE		39  /**/
#define ERR_ACN_ENCODE_TELECOMMAND_SUBSERVICE_TYPE		44  /**/
#define ERR_ACN_ENCODE_TELECOMMAND_PARAM		49  /**/

flag asn1SccTelecommand_ACN_Encode(const asn1SccTelecommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_TELECOMMAND		55  /**/
#define ERR_ACN_DECODE_TELECOMMAND_SERVICE_TYPE		40  /**/
#define ERR_ACN_DECODE_TELECOMMAND_SUBSERVICE_TYPE		45  /**/
#define ERR_ACN_DECODE_TELECOMMAND_PARAM		50  /**/
flag asn1SccTelecommand_ACN_Decode(asn1SccTelecommand* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1Real asn1SccPr_time;


flag asn1SccPr_time_Equal(const asn1SccPr_time* pVal1, const asn1SccPr_time* pVal2);

#define ERR_PR_TIME		56  /*(0.0..1000000.0)*/
flag asn1SccPr_time_IsConstraintValid(const asn1SccPr_time* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccPr_time asn1SccPr_time_constant;
#else
#define asn1SccPr_time_constant 0.0000000000000000000E+000
#endif

void asn1SccPr_time_Initialize(asn1SccPr_time* pVal);

#define ERR_UPER_ENCODE_PR_TIME		57  /**/
#define asn1SccPr_time_REQUIRED_BYTES_FOR_ENCODING       13
#define asn1SccPr_time_REQUIRED_BITS_FOR_ENCODING        104

flag asn1SccPr_time_Encode(const asn1SccPr_time* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PR_TIME		58  /**/
flag asn1SccPr_time_Decode(asn1SccPr_time* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccPr_time_REQUIRED_BYTES_FOR_ACN_ENCODING       13
#define asn1SccPr_time_REQUIRED_BITS_FOR_ACN_ENCODING        104

#define ERR_ACN_ENCODE_PR_TIME		59  /**/

flag asn1SccPr_time_ACN_Encode(const asn1SccPr_time* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PR_TIME		60  /**/
flag asn1SccPr_time_ACN_Decode(asn1SccPr_time* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int32;


flag asn1SccT_Int32_Equal(const asn1SccT_Int32* pVal1, const asn1SccT_Int32* pVal2);

#define ERR_T_INT32		61  /*(-2147483648 .. 2147483647)*/
flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Int32 asn1SccT_Int32_constant;
#else
#define asn1SccT_Int32_constant 0LL
#endif

void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal);

#define ERR_UPER_ENCODE_T_INT32		62  /**/
#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_Int32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_Int32_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT32		63  /**/
flag asn1SccT_Int32_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define asn1SccT_Int32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_INT32		64  /**/

flag asn1SccT_Int32_ACN_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_INT32		65  /**/
flag asn1SccT_Int32_ACN_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt32;


flag asn1SccT_UInt32_Equal(const asn1SccT_UInt32* pVal1, const asn1SccT_UInt32* pVal2);

#define ERR_T_UINT32		66  /*(0 .. 4294967295)*/
flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_UInt32 asn1SccT_UInt32_constant;
#else
#define asn1SccT_UInt32_constant 0UL
#endif

void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal);

#define ERR_UPER_ENCODE_T_UINT32		67  /**/
#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_UInt32_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT32		68  /**/
flag asn1SccT_UInt32_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_UINT32		69  /**/

flag asn1SccT_UInt32_ACN_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT32		70  /**/
flag asn1SccT_UInt32_ACN_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Runtime_Error --------------------------------------------*/

typedef enum {
    T_Runtime_Error_NONE,
    T_Runtime_Error_noerror_PRESENT,
    T_Runtime_Error_encodeerror_PRESENT,
    T_Runtime_Error_decodeerror_PRESENT
} asn1SccT_Runtime_Error_selection;

typedef union {
    asn1SccT_UInt32 noerror;
    asn1SccT_Int32 encodeerror;
    asn1SccT_Int32 decodeerror;
} asn1SccT_Runtime_Error_unchecked_union;

typedef struct {
    asn1SccT_Runtime_Error_selection kind;

    asn1SccT_Runtime_Error_unchecked_union u;
} asn1SccT_Runtime_Error;

flag asn1SccT_Runtime_Error_Equal(const asn1SccT_Runtime_Error* pVal1, const asn1SccT_Runtime_Error* pVal2);

#define ERR_T_RUNTIME_ERROR		101  /**/
#define ERR_T_RUNTIME_ERROR_NOERROR_2		76  /**/
#define ERR_T_RUNTIME_ERROR_ENCODEERROR_2		86  /**/
#define ERR_T_RUNTIME_ERROR_DECODEERROR_2		96  /**/
flag asn1SccT_Runtime_Error_IsConstraintValid(const asn1SccT_Runtime_Error* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Runtime_Error asn1SccT_Runtime_Error_constant;
#else
#define asn1SccT_Runtime_Error_constant {.kind = T_Runtime_Error_noerror_PRESENT, .u.noerror = 0UL}
#endif

void asn1SccT_Runtime_Error_Initialize(asn1SccT_Runtime_Error* pVal);

#define ERR_UPER_ENCODE_T_RUNTIME_ERROR		102  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_NOERROR_2		77  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		87  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		97  /**/
#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ENCODING       5
#define asn1SccT_Runtime_Error_REQUIRED_BITS_FOR_ENCODING        34

flag asn1SccT_Runtime_Error_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_RUNTIME_ERROR		103  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_NOERROR_2		78  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		88  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		98  /**/
flag asn1SccT_Runtime_Error_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ACN_ENCODING       5
#define asn1SccT_Runtime_Error_REQUIRED_BITS_FOR_ACN_ENCODING        34

#define ERR_ACN_ENCODE_T_RUNTIME_ERROR		104  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_NOERROR_2		79  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		89  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		99  /**/

flag asn1SccT_Runtime_Error_ACN_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_RUNTIME_ERROR		105  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_NOERROR_2		80  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		90  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		100  /**/
flag asn1SccT_Runtime_Error_ACN_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int8;


flag asn1SccT_Int8_Equal(const asn1SccT_Int8* pVal1, const asn1SccT_Int8* pVal2);

#define ERR_T_INT8		106  /*(-128 .. 127)*/
flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Int8 asn1SccT_Int8_constant;
#else
#define asn1SccT_Int8_constant 0LL
#endif

void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal);

#define ERR_UPER_ENCODE_T_INT8		107  /**/
#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Int8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_Int8_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT8		108  /**/
flag asn1SccT_Int8_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_Int8_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_T_INT8		109  /**/

flag asn1SccT_Int8_ACN_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_INT8		110  /**/
flag asn1SccT_Int8_ACN_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt8;


flag asn1SccT_UInt8_Equal(const asn1SccT_UInt8* pVal1, const asn1SccT_UInt8* pVal2);

#define ERR_T_UINT8		111  /*(0 .. 255)*/
flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_UInt8 asn1SccT_UInt8_constant;
#else
#define asn1SccT_UInt8_constant 0UL
#endif

void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal);

#define ERR_UPER_ENCODE_T_UINT8		112  /**/
#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_UInt8_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT8		113  /**/
flag asn1SccT_UInt8_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_T_UINT8		114  /**/

flag asn1SccT_UInt8_ACN_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT8		115  /**/
flag asn1SccT_UInt8_ACN_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccT_Boolean;


flag asn1SccT_Boolean_Equal(const asn1SccT_Boolean* pVal1, const asn1SccT_Boolean* pVal2);

#define ERR_T_BOOLEAN		116  /**/
flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Boolean asn1SccT_Boolean_constant;
#else
#define asn1SccT_Boolean_constant FALSE
#endif

void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal);

#define ERR_UPER_ENCODE_T_BOOLEAN		117  /**/
#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccT_Boolean_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_BOOLEAN		118  /**/
flag asn1SccT_Boolean_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_T_BOOLEAN		119  /**/

flag asn1SccT_Boolean_ACN_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_BOOLEAN		120  /**/
flag asn1SccT_Boolean_ACN_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Null_Record --------------------------------------------*/
typedef struct {

} asn1SccT_Null_Record;

flag asn1SccT_Null_Record_Equal(const asn1SccT_Null_Record* pVal1, const asn1SccT_Null_Record* pVal2);

#define ERR_T_NULL_RECORD		121  /**/
flag asn1SccT_Null_Record_IsConstraintValid(const asn1SccT_Null_Record* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Null_Record asn1SccT_Null_Record_constant;
#else
#define asn1SccT_Null_Record_constant {}
#endif

void asn1SccT_Null_Record_Initialize(asn1SccT_Null_Record* pVal);

#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ENCODING       0
#define asn1SccT_Null_Record_REQUIRED_BITS_FOR_ENCODING        0

flag asn1SccT_Null_Record_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccT_Null_Record_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ACN_ENCODING       0
#define asn1SccT_Null_Record_REQUIRED_BITS_FOR_ACN_ENCODING        0


flag asn1SccT_Null_Record_ACN_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccT_Null_Record_ACN_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccPID_Range;


flag asn1SccPID_Range_Equal(const asn1SccPID_Range* pVal1, const asn1SccPID_Range* pVal2);

#define ERR_PID_RANGE		126  /*(0..4)*/
flag asn1SccPID_Range_IsConstraintValid(const asn1SccPID_Range* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccPID_Range asn1SccPID_Range_constant;
#else
#define asn1SccPID_Range_constant 0UL
#endif

void asn1SccPID_Range_Initialize(asn1SccPID_Range* pVal);

#define ERR_UPER_ENCODE_PID_RANGE		127  /**/
#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_Range_REQUIRED_BITS_FOR_ENCODING        3

flag asn1SccPID_Range_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID_RANGE		128  /**/
flag asn1SccPID_Range_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccPID_Range_REQUIRED_BITS_FOR_ACN_ENCODING        3

#define ERR_ACN_ENCODE_PID_RANGE		129  /**/

flag asn1SccPID_Range_ACN_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PID_RANGE		130  /**/
flag asn1SccPID_Range_ACN_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    PID_bkgtcexec = 0,
    PID_hkfdirmng = 1,
    PID_legacy = 2,
    PID_tcmanager = 3,
    PID_env = 4
} asn1SccPID;

// please use the following macros to avoid breaking code.
#define asn1SccPID_bkgtcexec PID_bkgtcexec
#define asn1SccPID_hkfdirmng PID_hkfdirmng
#define asn1SccPID_legacy PID_legacy
#define asn1SccPID_tcmanager PID_tcmanager
#define asn1SccPID_env PID_env

flag asn1SccPID_Equal(const asn1SccPID* pVal1, const asn1SccPID* pVal2);

#define ERR_PID		131  /*bkgtcexec | hkfdirmng | legacy | tcmanager | env*/
flag asn1SccPID_IsConstraintValid(const asn1SccPID* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccPID asn1SccPID_constant;
#else
#define asn1SccPID_constant PID_bkgtcexec
#endif

void asn1SccPID_Initialize(asn1SccPID* pVal);

#define ERR_UPER_ENCODE_PID		132  /**/
#define asn1SccPID_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_REQUIRED_BITS_FOR_ENCODING        3

flag asn1SccPID_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID		133  /**/
flag asn1SccPID_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccPID_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccPID_REQUIRED_BITS_FOR_ACN_ENCODING        3

#define ERR_ACN_ENCODE_PID		134  /**/

flag asn1SccPID_ACN_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PID		135  /**/
flag asn1SccPID_ACN_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
