/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "asn1crt_encoding_acn.h"

#include "dataview-uniq.h"



flag asn1SccRawTC_Equal(const asn1SccRawTC* pVal1, const asn1SccRawTC* pVal2)
{
	return (pVal1->nCount == pVal2->nCount) && (memcmp(pVal1->arr, pVal2->arr, pVal1->nCount) ==0);

}

flag asn1SccRawTC_IsConstraintValid(const asn1SccRawTC* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = (pVal->nCount <= 256);
    *pErrCode = ret ? 0 :  ERR_RAWTC;

	return ret;
}

#ifdef __cplusplus
const asn1SccRawTC asn1SccRawTC_constant = {.nCount = 0, .arr  = {[0 ... 256-1] = 0 }};
#endif

void asn1SccRawTC_Initialize(asn1SccRawTC* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccRawTC)asn1SccRawTC_constant;
}

flag asn1SccRawTC_Encode(const asn1SccRawTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccRawTC_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 0, 256);
	    ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->arr, pVal->nCount);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccRawTC_Decode(asn1SccRawTC* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint nCount;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 256);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_RAWTC;
	pVal->nCount = (long)nCount;
	ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->arr, pVal->nCount);

	return ret  && asn1SccRawTC_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccRawTC_ACN_Encode(const asn1SccRawTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccRawTC_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 0, 256);
	    ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->arr, pVal->nCount);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccRawTC_ACN_Decode(asn1SccRawTC* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint nCount;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 256);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_RAWTC;
	pVal->nCount = (long)nCount;
	ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->arr, pVal->nCount);

    return ret && asn1SccRawTC_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccRxTC_Equal(const asn1SccRxTC* pVal1, const asn1SccRxTC* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccRxTC_IsConstraintValid(const asn1SccRxTC* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((*(pVal)) == RxTC_not_accepted)) || (((*(pVal)) == RxTC_accepted)));
    *pErrCode = ret ? 0 :  ERR_RXTC;

	return ret;
}

#ifdef __cplusplus
const asn1SccRxTC asn1SccRxTC_constant = RxTC_not_accepted;
#endif

void asn1SccRxTC_Initialize(asn1SccRxTC* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccRxTC)asn1SccRxTC_constant;
}

flag asn1SccRxTC_Encode(const asn1SccRxTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccRxTC_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal)))
	    {
	        case RxTC_not_accepted:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 1);
	        	break;
	        case RxTC_accepted:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 1);
	        	break;
	        default:                    /*COVERAGE_IGNORE*/
	    	    *pErrCode = ERR_UPER_ENCODE_RXTC; /*COVERAGE_IGNORE*/
	    	    ret = FALSE;            /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccRxTC_Decode(asn1SccRxTC* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	{
	    asn1SccSint enumIndex;
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 1);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_RXTC;
	    if (ret) {
	        switch(enumIndex)
	        {
	            case 0:
	                (*(pVal)) = RxTC_not_accepted;
	                break;
	            case 1:
	                (*(pVal)) = RxTC_accepted;
	                break;
	            default:                        /*COVERAGE_IGNORE*/
		            *pErrCode = ERR_UPER_DECODE_RXTC;     /*COVERAGE_IGNORE*/
		            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } else {
	        (*(pVal)) = RxTC_not_accepted;             /*COVERAGE_IGNORE*/
	    }
	}

	return ret  && asn1SccRxTC_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccRxTC_ACN_Encode(const asn1SccRxTC* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint intVal_pVal;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccRxTC_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal))) {
	        case RxTC_not_accepted:
	            intVal_pVal = 0UL;
	            break;
	        case RxTC_accepted:
	            intVal_pVal = 1UL;
	            break;
	        default:                                    /*COVERAGE_IGNORE*/
	            ret = FALSE;                            /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_ENCODE_RXTC;                 /*COVERAGE_IGNORE*/
	    }
	    if (ret) {
	    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal_pVal, 0, 1);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccRxTC_ACN_Decode(asn1SccRxTC* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint intVal_pVal;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(intVal_pVal)), 0, 1);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_RXTC;
	if (ret) {
	    switch (intVal_pVal) {
	        case 0:
	            (*(pVal)) = RxTC_not_accepted;
	            break;
	        case 1:
	            (*(pVal)) = RxTC_accepted;
	            break;
	    default:                                    /*COVERAGE_IGNORE*/
	        ret = FALSE;                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_RXTC;                 /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccRxTC_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccFwdCommand_Equal(const asn1SccFwdCommand* pVal1, const asn1SccFwdCommand* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccFwdCommand_IsConstraintValid(const asn1SccFwdCommand* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((*(pVal)) == FwdCommand_to_reboot)) || (((*(pVal)) == FwdCommand_exec_prio_tc)))) || (((*(pVal)) == FwdCommand_fwdhk_fdir_tc)))) || (((*(pVal)) == FwdCommand_fwdbkgtc)));
    *pErrCode = ret ? 0 :  ERR_FWDCOMMAND;

	return ret;
}

#ifdef __cplusplus
const asn1SccFwdCommand asn1SccFwdCommand_constant = FwdCommand_to_reboot;
#endif

void asn1SccFwdCommand_Initialize(asn1SccFwdCommand* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccFwdCommand)asn1SccFwdCommand_constant;
}

flag asn1SccFwdCommand_Encode(const asn1SccFwdCommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccFwdCommand_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal)))
	    {
	        case FwdCommand_to_reboot:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 3);
	        	break;
	        case FwdCommand_exec_prio_tc:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 3);
	        	break;
	        case FwdCommand_fwdhk_fdir_tc:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 3);
	        	break;
	        case FwdCommand_fwdbkgtc:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 3);
	        	break;
	        default:                    /*COVERAGE_IGNORE*/
	    	    *pErrCode = ERR_UPER_ENCODE_FWDCOMMAND; /*COVERAGE_IGNORE*/
	    	    ret = FALSE;            /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccFwdCommand_Decode(asn1SccFwdCommand* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	{
	    asn1SccSint enumIndex;
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 3);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_FWDCOMMAND;
	    if (ret) {
	        switch(enumIndex)
	        {
	            case 0:
	                (*(pVal)) = FwdCommand_to_reboot;
	                break;
	            case 1:
	                (*(pVal)) = FwdCommand_exec_prio_tc;
	                break;
	            case 2:
	                (*(pVal)) = FwdCommand_fwdhk_fdir_tc;
	                break;
	            case 3:
	                (*(pVal)) = FwdCommand_fwdbkgtc;
	                break;
	            default:                        /*COVERAGE_IGNORE*/
		            *pErrCode = ERR_UPER_DECODE_FWDCOMMAND;     /*COVERAGE_IGNORE*/
		            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } else {
	        (*(pVal)) = FwdCommand_to_reboot;             /*COVERAGE_IGNORE*/
	    }
	}

	return ret  && asn1SccFwdCommand_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccFwdCommand_ACN_Encode(const asn1SccFwdCommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint intVal_pVal;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccFwdCommand_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal))) {
	        case FwdCommand_to_reboot:
	            intVal_pVal = 0UL;
	            break;
	        case FwdCommand_exec_prio_tc:
	            intVal_pVal = 1UL;
	            break;
	        case FwdCommand_fwdhk_fdir_tc:
	            intVal_pVal = 2UL;
	            break;
	        case FwdCommand_fwdbkgtc:
	            intVal_pVal = 3UL;
	            break;
	        default:                                    /*COVERAGE_IGNORE*/
	            ret = FALSE;                            /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_ENCODE_FWDCOMMAND;                 /*COVERAGE_IGNORE*/
	    }
	    if (ret) {
	    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal_pVal, 0, 3);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccFwdCommand_ACN_Decode(asn1SccFwdCommand* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint intVal_pVal;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(intVal_pVal)), 0, 3);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_FWDCOMMAND;
	if (ret) {
	    switch (intVal_pVal) {
	        case 0:
	            (*(pVal)) = FwdCommand_to_reboot;
	            break;
	        case 1:
	            (*(pVal)) = FwdCommand_exec_prio_tc;
	            break;
	        case 2:
	            (*(pVal)) = FwdCommand_fwdhk_fdir_tc;
	            break;
	        case 3:
	            (*(pVal)) = FwdCommand_fwdbkgtc;
	            break;
	    default:                                    /*COVERAGE_IGNORE*/
	        ret = FALSE;                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_FWDCOMMAND;                 /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccFwdCommand_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccGPendingEvAction_Equal(const asn1SccGPendingEvAction* pVal1, const asn1SccGPendingEvAction* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccGPendingEvAction_IsConstraintValid(const asn1SccGPendingEvAction* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

#ifdef __cplusplus
const asn1SccGPendingEvAction asn1SccGPendingEvAction_constant = FALSE;
#endif

void asn1SccGPendingEvAction_Initialize(asn1SccGPendingEvAction* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccGPendingEvAction)asn1SccGPendingEvAction_constant;
}

flag asn1SccGPendingEvAction_Encode(const asn1SccGPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccGPendingEvAction_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccGPendingEvAction_Decode(asn1SccGPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_GPENDINGEVACTION;

	return ret  && asn1SccGPendingEvAction_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccGPendingEvAction_ACN_Encode(const asn1SccGPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccGPendingEvAction_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccGPendingEvAction_ACN_Decode(asn1SccGPendingEvAction* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_GPENDINGEVACTION;

    return ret && asn1SccGPendingEvAction_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccGToReboot_Equal(const asn1SccGToReboot* pVal1, const asn1SccGToReboot* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccGToReboot_IsConstraintValid(const asn1SccGToReboot* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

#ifdef __cplusplus
const asn1SccGToReboot asn1SccGToReboot_constant = FALSE;
#endif

void asn1SccGToReboot_Initialize(asn1SccGToReboot* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccGToReboot)asn1SccGToReboot_constant;
}

flag asn1SccGToReboot_Encode(const asn1SccGToReboot* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccGToReboot_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccGToReboot_Decode(asn1SccGToReboot* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_GTOREBOOT;

	return ret  && asn1SccGToReboot_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccGToReboot_ACN_Encode(const asn1SccGToReboot* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccGToReboot_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccGToReboot_ACN_Decode(asn1SccGToReboot* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_GTOREBOOT;

    return ret && asn1SccGToReboot_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccGFwToHK_FDIR_Equal(const asn1SccGFwToHK_FDIR* pVal1, const asn1SccGFwToHK_FDIR* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccGFwToHK_FDIR_IsConstraintValid(const asn1SccGFwToHK_FDIR* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

#ifdef __cplusplus
const asn1SccGFwToHK_FDIR asn1SccGFwToHK_FDIR_constant = FALSE;
#endif

void asn1SccGFwToHK_FDIR_Initialize(asn1SccGFwToHK_FDIR* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccGFwToHK_FDIR)asn1SccGFwToHK_FDIR_constant;
}

flag asn1SccGFwToHK_FDIR_Encode(const asn1SccGFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccGFwToHK_FDIR_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccGFwToHK_FDIR_Decode(asn1SccGFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_GFWTOHK_FDIR;

	return ret  && asn1SccGFwToHK_FDIR_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccGFwToHK_FDIR_ACN_Encode(const asn1SccGFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccGFwToHK_FDIR_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccGFwToHK_FDIR_ACN_Decode(asn1SccGFwToHK_FDIR* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_GFWTOHK_FDIR;

    return ret && asn1SccGFwToHK_FDIR_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccGFwToBKG_Equal(const asn1SccGFwToBKG* pVal1, const asn1SccGFwToBKG* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccGFwToBKG_IsConstraintValid(const asn1SccGFwToBKG* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

#ifdef __cplusplus
const asn1SccGFwToBKG asn1SccGFwToBKG_constant = FALSE;
#endif

void asn1SccGFwToBKG_Initialize(asn1SccGFwToBKG* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccGFwToBKG)asn1SccGFwToBKG_constant;
}

flag asn1SccGFwToBKG_Encode(const asn1SccGFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccGFwToBKG_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccGFwToBKG_Decode(asn1SccGFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_GFWTOBKG;

	return ret  && asn1SccGFwToBKG_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccGFwToBKG_ACN_Encode(const asn1SccGFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccGFwToBKG_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccGFwToBKG_ACN_Decode(asn1SccGFwToBKG* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_GFWTOBKG;

    return ret && asn1SccGFwToBKG_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccTelecommand_service_type_Equal(const asn1SccTelecommand_service_type* pVal1, const asn1SccTelecommand_service_type* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccTelecommand_subservice_type_Equal(const asn1SccTelecommand_subservice_type* pVal1, const asn1SccTelecommand_subservice_type* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccTelecommand_param_Equal(const asn1SccTelecommand_param* pVal1, const asn1SccTelecommand_param* pVal2)
{
	return memcmp(pVal1->arr, pVal2->arr, 3) ==0;

}

flag asn1SccTelecommand_Equal(const asn1SccTelecommand* pVal1, const asn1SccTelecommand* pVal2)
{
	flag ret=TRUE;

    ret = asn1SccTelecommand_service_type_Equal((&(pVal1->service_type)), (&(pVal2->service_type)));

    if (ret) {
        ret = asn1SccTelecommand_subservice_type_Equal((&(pVal1->subservice_type)), (&(pVal2->subservice_type)));

        if (ret) {
            ret = asn1SccTelecommand_param_Equal((&(pVal1->param)), (&(pVal2->param)));

        }

    }

	return ret;

}

flag asn1SccTelecommand_service_type_IsConstraintValid(const asn1SccTelecommand_service_type* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_TELECOMMAND_SERVICE_TYPE;

	return ret;
}

flag asn1SccTelecommand_subservice_type_IsConstraintValid(const asn1SccTelecommand_subservice_type* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_TELECOMMAND_SUBSERVICE_TYPE;

	return ret;
}

flag asn1SccTelecommand_param_IsConstraintValid(const asn1SccTelecommand_param* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

flag asn1SccTelecommand_IsConstraintValid(const asn1SccTelecommand* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = asn1SccTelecommand_service_type_IsConstraintValid((&(pVal->service_type)), pErrCode);
    if (ret) {
        ret = asn1SccTelecommand_subservice_type_IsConstraintValid((&(pVal->subservice_type)), pErrCode);
        if (ret) {
            ret = asn1SccTelecommand_param_IsConstraintValid((&(pVal->param)), pErrCode);
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

#ifdef __cplusplus
const asn1SccTelecommand_service_type asn1SccTelecommand_service_type_constant = 0UL;
#endif
#ifdef __cplusplus
const asn1SccTelecommand_subservice_type asn1SccTelecommand_subservice_type_constant = 0UL;
#endif
#ifdef __cplusplus
const asn1SccTelecommand_param asn1SccTelecommand_param_constant = {.arr  = {[0 ... 3-1] = 0 }};
#endif
#ifdef __cplusplus
const asn1SccTelecommand asn1SccTelecommand_constant = {.service_type = 0UL, .subservice_type = 0UL, .param = {.arr  = {[0 ... 3-1] = 0 }}};
#endif

void asn1SccTelecommand_Initialize(asn1SccTelecommand* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccTelecommand)asn1SccTelecommand_constant;
}

flag asn1SccTelecommand_Encode(const asn1SccTelecommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccTelecommand_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode service_type */
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->service_type, 0, 255);
	    if (ret) {
	        /*Encode subservice_type */
	        BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->subservice_type, 0, 255);
	        if (ret) {
	            /*Encode param */
	            ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->param.arr, 3);
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccTelecommand_Decode(asn1SccTelecommand* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode service_type */
	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->service_type)), 0, 255);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELECOMMAND_SERVICE_TYPE;
	if (ret) {
	    /*Decode subservice_type */
	    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->subservice_type)), 0, 255);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELECOMMAND_SUBSERVICE_TYPE;
	    if (ret) {
	        /*Decode param */
	        ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->param.arr, 3);
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && asn1SccTelecommand_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccTelecommand_ACN_Encode(const asn1SccTelecommand* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccTelecommand_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode service_type */
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->service_type, 0, 255);
	    if (ret) {
	        /*Encode subservice_type */
	        BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->subservice_type, 0, 255);
	        if (ret) {
	            /*Encode param */
	            ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->param.arr, 3);
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccTelecommand_ACN_Decode(asn1SccTelecommand* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode service_type */
	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->service_type)), 0, 255);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_TELECOMMAND_SERVICE_TYPE;
	if (ret) {
	    /*Decode subservice_type */
	    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->subservice_type)), 0, 255);
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_TELECOMMAND_SUBSERVICE_TYPE;
	    if (ret) {
	        /*Decode param */
	        ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->param.arr, 3);
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

    return ret && asn1SccTelecommand_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccPr_time_Equal(const asn1SccPr_time* pVal1, const asn1SccPr_time* pVal2)
{
	return Asn1Real_Equal((*(pVal1)),(*(pVal2)));

}

flag asn1SccPr_time_IsConstraintValid(const asn1SccPr_time* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((0.0000000000000000000E+000 <= (*(pVal))) && ((*(pVal)) <= 1.0000000000000000000E+006));
    *pErrCode = ret ? 0 :  ERR_PR_TIME;

	return ret;
}

#ifdef __cplusplus
const asn1SccPr_time asn1SccPr_time_constant = 0.0000000000000000000E+000;
#endif

void asn1SccPr_time_Initialize(asn1SccPr_time* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccPr_time)asn1SccPr_time_constant;
}

flag asn1SccPr_time_Encode(const asn1SccPr_time* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPr_time_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPr_time_Decode(asn1SccPr_time* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_PR_TIME;

	return ret  && asn1SccPr_time_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccPr_time_ACN_Encode(const asn1SccPr_time* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPr_time_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPr_time_ACN_Decode(asn1SccPr_time* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PR_TIME;

    return ret && asn1SccPr_time_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Int32_Equal(const asn1SccT_Int32* pVal1, const asn1SccT_Int32* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-2147483648LL <= (*(pVal))) && ((*(pVal)) <= 2147483647LL));
    *pErrCode = ret ? 0 :  ERR_T_INT32;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Int32 asn1SccT_Int32_constant = 0LL;
#endif

void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Int32)asn1SccT_Int32_constant;
}

flag asn1SccT_Int32_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -2147483648LL, 2147483647LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int32_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_INT32;

	return ret  && asn1SccT_Int32_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Int32_ACN_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -2147483648LL, 2147483647LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int32_ACN_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_INT32;

    return ret && asn1SccT_Int32_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_UInt32_Equal(const asn1SccT_UInt32* pVal1, const asn1SccT_UInt32* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4294967295UL);
    *pErrCode = ret ? 0 :  ERR_T_UINT32;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_UInt32 asn1SccT_UInt32_constant = 0UL;
#endif

void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_UInt32)asn1SccT_UInt32_constant;
}

flag asn1SccT_UInt32_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967295LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt32_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_UINT32;

	return ret  && asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_UInt32_ACN_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967295LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt32_ACN_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_UINT32;

    return ret && asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Runtime_Error_Equal(const asn1SccT_Runtime_Error* pVal1, const asn1SccT_Runtime_Error* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->kind == pVal2->kind);
    if (ret) {
    	switch(pVal1->kind)
    	{
    	case T_Runtime_Error_noerror_PRESENT:
    		ret = (pVal1->u.noerror == pVal2->u.noerror);
    		break;
    	case T_Runtime_Error_encodeerror_PRESENT:
    		ret = (pVal1->u.encodeerror == pVal2->u.encodeerror);
    		break;
    	case T_Runtime_Error_decodeerror_PRESENT:
    		ret = (pVal1->u.decodeerror == pVal2->u.decodeerror);
    		break;
    	default: /*COVERAGE_IGNORE*/
    		ret = FALSE;    /*COVERAGE_IGNORE*/
    	}
    } /*COVERAGE_IGNORE*/
	return ret;

}

flag asn1SccT_Runtime_Error_IsConstraintValid(const asn1SccT_Runtime_Error* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case T_Runtime_Error_noerror_PRESENT : 
            ret = asn1SccT_UInt32_IsConstraintValid((&(pVal->u.noerror)), pErrCode);
            break;          
        case T_Runtime_Error_encodeerror_PRESENT : 
            ret = asn1SccT_Int32_IsConstraintValid((&(pVal->u.encodeerror)), pErrCode);
            break;          
        case T_Runtime_Error_decodeerror_PRESENT : 
            ret = asn1SccT_Int32_IsConstraintValid((&(pVal->u.decodeerror)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_T_RUNTIME_ERROR;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Runtime_Error asn1SccT_Runtime_Error_constant = {.kind = T_Runtime_Error_noerror_PRESENT, .u.noerror = 0UL};
#endif

void asn1SccT_Runtime_Error_Initialize(asn1SccT_Runtime_Error* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Runtime_Error)asn1SccT_Runtime_Error_constant;
}

flag asn1SccT_Runtime_Error_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch(pVal->kind)
	    {
	    case T_Runtime_Error_noerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	    	ret = asn1SccT_UInt32_Encode((&(pVal->u.noerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_encodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	    	ret = asn1SccT_Int32_Encode((&(pVal->u.encodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_decodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	    	ret = asn1SccT_Int32_Encode((&(pVal->u.decodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    default:                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_ENCODE_T_RUNTIME_ERROR;         /*COVERAGE_IGNORE*/
	        ret = FALSE;                    /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Runtime_Error_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint asn1SccT_Runtime_Error_index_tmp;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &asn1SccT_Runtime_Error_index_tmp, 0, 2);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_RUNTIME_ERROR;
	if (ret) {
	    switch(asn1SccT_Runtime_Error_index_tmp)
	    {
	    case 0:
	    	pVal->kind = T_Runtime_Error_noerror_PRESENT;
	    	ret = asn1SccT_UInt32_Decode((&(pVal->u.noerror)), pBitStrm, pErrCode);
	    	break;
	    case 1:
	    	pVal->kind = T_Runtime_Error_encodeerror_PRESENT;
	    	ret = asn1SccT_Int32_Decode((&(pVal->u.encodeerror)), pBitStrm, pErrCode);
	    	break;
	    case 2:
	    	pVal->kind = T_Runtime_Error_decodeerror_PRESENT;
	    	ret = asn1SccT_Int32_Decode((&(pVal->u.decodeerror)), pBitStrm, pErrCode);
	    	break;
	    default:                        /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_DECODE_T_RUNTIME_ERROR;     /*COVERAGE_IGNORE*/
	        ret = FALSE;                /*COVERAGE_IGNORE*/
	    }
	}  /*COVERAGE_IGNORE*/

	return ret  && asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Runtime_Error_ACN_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch(pVal->kind)
	    {
	    case T_Runtime_Error_noerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	    	ret = asn1SccT_UInt32_ACN_Encode((&(pVal->u.noerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_encodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	    	ret = asn1SccT_Int32_ACN_Encode((&(pVal->u.encodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_decodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	    	ret = asn1SccT_Int32_ACN_Encode((&(pVal->u.decodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    default: /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_ENCODE_T_RUNTIME_ERROR;         /*COVERAGE_IGNORE*/
	        ret = FALSE;                    /*COVERAGE_IGNORE*/
	    } /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Runtime_Error_ACN_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint TASTE_BasicTypes_T_Runtime_Error_index_tmp;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &TASTE_BasicTypes_T_Runtime_Error_index_tmp, 0, 2);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_RUNTIME_ERROR;
	if (ret) {
	    switch(TASTE_BasicTypes_T_Runtime_Error_index_tmp)
	    {
	    case 0:
	    	pVal->kind = T_Runtime_Error_noerror_PRESENT;
	    	ret = asn1SccT_UInt32_ACN_Decode((&(pVal->u.noerror)), pBitStrm, pErrCode);
	    	break;
	    case 1:
	    	pVal->kind = T_Runtime_Error_encodeerror_PRESENT;
	    	ret = asn1SccT_Int32_ACN_Decode((&(pVal->u.encodeerror)), pBitStrm, pErrCode);
	    	break;
	    case 2:
	    	pVal->kind = T_Runtime_Error_decodeerror_PRESENT;
	    	ret = asn1SccT_Int32_ACN_Decode((&(pVal->u.decodeerror)), pBitStrm, pErrCode);
	    	break;
	    default: /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_T_RUNTIME_ERROR;     /*COVERAGE_IGNORE*/
	        ret = FALSE;                /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Int8_Equal(const asn1SccT_Int8* pVal1, const asn1SccT_Int8* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-128LL <= (*(pVal))) && ((*(pVal)) <= 127LL));
    *pErrCode = ret ? 0 :  ERR_T_INT8;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Int8 asn1SccT_Int8_constant = 0LL;
#endif

void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Int8)asn1SccT_Int8_constant;
}

flag asn1SccT_Int8_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -128, 127);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int8_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -128, 127);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_INT8;

	return ret  && asn1SccT_Int8_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Int8_ACN_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -128, 127);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int8_ACN_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -128, 127);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_INT8;

    return ret && asn1SccT_Int8_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_UInt8_Equal(const asn1SccT_UInt8* pVal1, const asn1SccT_UInt8* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_T_UINT8;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_UInt8 asn1SccT_UInt8_constant = 0UL;
#endif

void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_UInt8)asn1SccT_UInt8_constant;
}

flag asn1SccT_UInt8_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 255);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt8_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 255);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_UINT8;

	return ret  && asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_UInt8_ACN_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 255);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt8_ACN_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 255);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_UINT8;

    return ret && asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Boolean_Equal(const asn1SccT_Boolean* pVal1, const asn1SccT_Boolean* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Boolean asn1SccT_Boolean_constant = FALSE;
#endif

void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Boolean)asn1SccT_Boolean_constant;
}

flag asn1SccT_Boolean_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Boolean_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_BOOLEAN;

	return ret  && asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Boolean_ACN_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Boolean_ACN_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_BOOLEAN;

    return ret && asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Null_Record_Equal(const asn1SccT_Null_Record* pVal1, const asn1SccT_Null_Record* pVal2)
{
	(void)pVal1;
	(void)pVal2;
	return TRUE;

}

flag asn1SccT_Null_Record_IsConstraintValid(const asn1SccT_Null_Record* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Null_Record asn1SccT_Null_Record_constant = {};
#endif

void asn1SccT_Null_Record_Initialize(asn1SccT_Null_Record* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Null_Record)asn1SccT_Null_Record_constant;
}

flag asn1SccT_Null_Record_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Null_Record_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;



	return ret  && asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Null_Record_ACN_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Null_Record_ACN_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	(void)pBitStrm;
	*pErrCode = 0;



    return ret && asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccPID_Range_Equal(const asn1SccPID_Range* pVal1, const asn1SccPID_Range* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccPID_Range_IsConstraintValid(const asn1SccPID_Range* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4UL);
    *pErrCode = ret ? 0 :  ERR_PID_RANGE;

	return ret;
}

#ifdef __cplusplus
const asn1SccPID_Range asn1SccPID_Range_constant = 0UL;
#endif

void asn1SccPID_Range_Initialize(asn1SccPID_Range* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccPID_Range)asn1SccPID_Range_constant;
}

flag asn1SccPID_Range_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_Range_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_Range_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_PID_RANGE;

	return ret  && asn1SccPID_Range_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccPID_Range_ACN_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_Range_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_Range_ACN_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PID_RANGE;

    return ret && asn1SccPID_Range_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccPID_Equal(const asn1SccPID* pVal1, const asn1SccPID* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccPID_IsConstraintValid(const asn1SccPID* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((((*(pVal)) == PID_bkgtcexec)) || (((*(pVal)) == PID_hkfdirmng)))) || (((*(pVal)) == PID_legacy)))) || (((*(pVal)) == PID_tcmanager)))) || (((*(pVal)) == PID_env)));
    *pErrCode = ret ? 0 :  ERR_PID;

	return ret;
}

#ifdef __cplusplus
const asn1SccPID asn1SccPID_constant = PID_bkgtcexec;
#endif

void asn1SccPID_Initialize(asn1SccPID* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccPID)asn1SccPID_constant;
}

flag asn1SccPID_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal)))
	    {
	        case PID_bkgtcexec:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 4);
	        	break;
	        case PID_hkfdirmng:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 4);
	        	break;
	        case PID_legacy:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 4);
	        	break;
	        case PID_tcmanager:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 4);
	        	break;
	        case PID_env:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 4, 0, 4);
	        	break;
	        default:                    /*COVERAGE_IGNORE*/
	    	    *pErrCode = ERR_UPER_ENCODE_PID; /*COVERAGE_IGNORE*/
	    	    ret = FALSE;            /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	{
	    asn1SccSint enumIndex;
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 4);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_PID;
	    if (ret) {
	        switch(enumIndex)
	        {
	            case 0:
	                (*(pVal)) = PID_bkgtcexec;
	                break;
	            case 1:
	                (*(pVal)) = PID_hkfdirmng;
	                break;
	            case 2:
	                (*(pVal)) = PID_legacy;
	                break;
	            case 3:
	                (*(pVal)) = PID_tcmanager;
	                break;
	            case 4:
	                (*(pVal)) = PID_env;
	                break;
	            default:                        /*COVERAGE_IGNORE*/
		            *pErrCode = ERR_UPER_DECODE_PID;     /*COVERAGE_IGNORE*/
		            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } else {
	        (*(pVal)) = PID_bkgtcexec;             /*COVERAGE_IGNORE*/
	    }
	}

	return ret  && asn1SccPID_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccPID_ACN_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint intVal_pVal;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal))) {
	        case PID_bkgtcexec:
	            intVal_pVal = 0UL;
	            break;
	        case PID_hkfdirmng:
	            intVal_pVal = 1UL;
	            break;
	        case PID_legacy:
	            intVal_pVal = 2UL;
	            break;
	        case PID_tcmanager:
	            intVal_pVal = 3UL;
	            break;
	        case PID_env:
	            intVal_pVal = 4UL;
	            break;
	        default:                                    /*COVERAGE_IGNORE*/
	            ret = FALSE;                            /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_ENCODE_PID;                 /*COVERAGE_IGNORE*/
	    }
	    if (ret) {
	    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal_pVal, 0, 4);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_ACN_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint intVal_pVal;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(intVal_pVal)), 0, 4);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PID;
	if (ret) {
	    switch (intVal_pVal) {
	        case 0:
	            (*(pVal)) = PID_bkgtcexec;
	            break;
	        case 1:
	            (*(pVal)) = PID_hkfdirmng;
	            break;
	        case 2:
	            (*(pVal)) = PID_legacy;
	            break;
	        case 3:
	            (*(pVal)) = PID_tcmanager;
	            break;
	        case 4:
	            (*(pVal)) = PID_env;
	            break;
	    default:                                    /*COVERAGE_IGNORE*/
	        ret = FALSE;                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_PID;                 /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccPID_IsConstraintValid(pVal, pErrCode);
}


