#ifndef __PRINTTYPESASASN1_H__
#define __PRINTTYPESASASN1_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintASN1RawTC(const char *paramName, const asn1SccRawTC *pData);
void PrintASN1RxTC(const char *paramName, const asn1SccRxTC *pData);
void PrintASN1FwdCommand(const char *paramName, const asn1SccFwdCommand *pData);
void PrintASN1GPendingEvAction(const char *paramName, const asn1SccGPendingEvAction *pData);
void PrintASN1GToReboot(const char *paramName, const asn1SccGToReboot *pData);
void PrintASN1GFwToHK_FDIR(const char *paramName, const asn1SccGFwToHK_FDIR *pData);
void PrintASN1GFwToBKG(const char *paramName, const asn1SccGFwToBKG *pData);
void PrintASN1Telecommand(const char *paramName, const asn1SccTelecommand *pData);
void PrintASN1Pr_time(const char *paramName, const asn1SccPr_time *pData);
void PrintASN1T_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintASN1T_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintASN1T_Runtime_Error(const char *paramName, const asn1SccT_Runtime_Error *pData);
void PrintASN1T_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintASN1T_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintASN1T_Boolean(const char *paramName, const asn1SccT_Boolean *pData);
void PrintASN1T_Null_Record(const char *paramName, const asn1SccT_Null_Record *pData);
void PrintASN1PID_Range(const char *paramName, const asn1SccPID_Range *pData);
void PrintASN1PID(const char *paramName, const asn1SccPID *pData);

#ifdef __cplusplus
}
#endif

#endif
