// Autogenerated code (from TASTE/Kazoo) : DO NOT EDIT

#include "demo_timer_manager.h"

// When hkfdirmng_hkfdirtimer expires, this function is called:
extern void demo_timer_manager_RI_hkfdirmng_hkfdirtimer(void);

void demo_timer_manager_startup(void)
{
 // Timer start up (nothing to do)
}

void demo_timer_manager_PI_Tick(void)
{
   if (active == timers[hkfdirmng_hkfdirtimer].state && 0 == -- timers[hkfdirmng_hkfdirtimer].value) {
      demo_timer_manager_RI_hkfdirmng_hkfdirtimer();
      timers[hkfdirmng_hkfdirtimer].state = inactive;
   }

}

void demo_timer_manager_PI_SET_hkfdirmng_hkfdirtimer(asn1SccT_UInt32 *val)
{
   /* Timer value must be multiple of 10 ms */
   assert (0 == (*val % 10));
   timers[hkfdirmng_hkfdirtimer].state = active;
   timers[hkfdirmng_hkfdirtimer].value = *val / 10;
}

void demo_timer_manager_PI_RESET_hkfdirmng_hkfdirtimer(void)
{
   timers[hkfdirmng_hkfdirtimer].state = inactive;
}


